{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"methods"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGBank","preciseIdentifier":"c:@M@iMojeSDK@objc(cs)INGBank","text":"INGBank"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/imojesdk\/ingpaymentmethodview\/methods"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGPaymentMethodView\/methods","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"methods"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"INGBank","preciseIdentifier":"c:@M@iMojeSDK@objc(cs)INGBank"},{"kind":"text","text":"]"}],"title":"methods","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:8iMojeSDK20INGPaymentMethodViewC7methodsSayAA7INGBankCGvp","modules":[{"name":"iMojeSDK"}]},"hierarchy":{"paths":[["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGPaymentMethodView"]]},"references":{"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGPaymentMethodView/methods":{"role":"symbol","title":"methods","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"methods"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"INGBank","preciseIdentifier":"c:@M@iMojeSDK@objc(cs)INGBank"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGPaymentMethodView\/methods","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk\/ingpaymentmethodview\/methods"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGBank":{"role":"symbol","title":"INGBank","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGBank"}],"abstract":[{"type":"text","text":":nodoc:"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGBank","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"INGBank"}],"url":"\/documentation\/imojesdk\/ingbank"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK":{"role":"collection","title":"iMojeSDK","abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGPaymentMethodView":{"role":"symbol","title":"INGPaymentMethodView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGPaymentMethodView"}],"abstract":[{"type":"text","text":"List payment method code view"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGPaymentMethodView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"INGPaymentMethodView"}],"url":"\/documentation\/imojesdk\/ingpaymentmethodview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGBank\/title","value":"INGBank"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGBank\/fragments","value":[{"kind":"identifier","text":"INGBank"}]},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGPaymentMethodView\/title","value":"INGPaymentMethodView"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGPaymentMethodView\/fragments","value":[{"kind":"identifier","text":"INGPaymentMethodView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}