{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"dynamic"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"numbersOfColumn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/imojesdk\/ingpaymentmethodview\/numbersofcolumn"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/imojesdk\/ingpaymentmethodview\/numbersofcolumn"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGPaymentMethodView\/numbersOfColumn","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"numbers of bank item on row"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"numbersOfColumn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"title":"numbersOfColumn","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@iMojeSDK@objc(cs)INGPaymentMethodView(py)numbersOfColumn","modules":[{"name":"iMojeSDK"}],"navigatorTitle":[{"kind":"identifier","text":"numbersOfColumn"}]},"hierarchy":{"paths":[["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGPaymentMethodView"]]},"references":{"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGPaymentMethodView/numbersOfColumn":{"role":"symbol","title":"numbersOfColumn","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"numbersOfColumn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"numbers of bank item on row"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGPaymentMethodView\/numbersOfColumn","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"numbersOfColumn"}],"url":"\/documentation\/imojesdk\/ingpaymentmethodview\/numbersofcolumn"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK":{"role":"collection","title":"iMojeSDK","abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGPaymentMethodView":{"role":"symbol","title":"INGPaymentMethodView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGPaymentMethodView"}],"abstract":[{"type":"text","text":"List payment method code view"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGPaymentMethodView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"INGPaymentMethodView"}],"url":"\/documentation\/imojesdk\/ingpaymentmethodview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"numbersOfColumn"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"numbersOfColumn"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"numbersOfColumn"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGPaymentMethodView~1numbersOfColumn\/title","value":"numbersOfColumn"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGPaymentMethodView~1numbersOfColumn\/fragments","value":[{"kind":"identifier","text":"numbersOfColumn"}]},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGPaymentMethodView\/title","value":"INGPaymentMethodView"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGPaymentMethodView\/fragments","value":[{"kind":"identifier","text":"INGPaymentMethodView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}