{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"applePayNotSupported"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/imojesdk\/imojesdkerror\/applepaynotsupported"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/imojesdk\/imojesdkerror\/applepaynotsupported"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError\/applePayNotSupported","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Rise when ApplePay is not supported"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"applePayNotSupported"}],"title":"iMojeSDKError.applePayNotSupported","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@iMojeSDK@E@iMojeSDKError@iMojeSDKErrorApplePayNotSupported","modules":[{"name":"iMojeSDK"}],"navigatorTitle":[{"kind":"identifier","text":"iMojeSDKErrorApplePayNotSupported"}]},"hierarchy":{"paths":[["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError"]]},"references":{"doc://pl.netizens.imojesdk/documentation/iMojeSDK/iMojeSDKError/applePayNotSupported":{"role":"symbol","title":"iMojeSDKError.applePayNotSupported","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"applePayNotSupported"}],"abstract":[{"type":"text","text":"Rise when ApplePay is not supported"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError\/applePayNotSupported","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"iMojeSDKErrorApplePayNotSupported"}],"url":"\/documentation\/imojesdk\/imojesdkerror\/applepaynotsupported"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK":{"role":"collection","title":"iMojeSDK","abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/iMojeSDKError":{"role":"symbol","title":"iMojeSDKError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"iMojeSDKError"}],"abstract":[{"type":"text","text":"iMojeSDKError"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"iMojeSDKError"}],"url":"\/documentation\/imojesdk\/imojesdkerror"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"iMojeSDKErrorApplePayNotSupported"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"iMojeSDKErrorApplePayNotSupported"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"iMojeSDKErrorApplePayNotSupported"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1iMojeSDKError~1applePayNotSupported\/title","value":"iMojeSDKErrorApplePayNotSupported"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1iMojeSDKError~1applePayNotSupported\/fragments","value":[{"kind":"identifier","text":"iMojeSDKErrorApplePayNotSupported"}]},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1iMojeSDKError\/title","value":"iMojeSDKError"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1iMojeSDKError\/fragments","value":[{"kind":"identifier","text":"iMojeSDKError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}