{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"emptyPaymentMethodCode"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/imojesdk\/imojesdkerror\/emptypaymentmethodcode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/imojesdk\/imojesdkerror\/emptypaymentmethodcode"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError\/emptyPaymentMethodCode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Raise when service has empty payment method code"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"emptyPaymentMethodCode"}],"title":"iMojeSDKError.emptyPaymentMethodCode","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@iMojeSDK@E@iMojeSDKError@iMojeSDKErrorEmptyPaymentMethodCode","modules":[{"name":"iMojeSDK"}],"navigatorTitle":[{"kind":"identifier","text":"iMojeSDKErrorEmptyPaymentMethodCode"}]},"hierarchy":{"paths":[["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError"]]},"references":{"doc://pl.netizens.imojesdk/documentation/iMojeSDK/iMojeSDKError/emptyPaymentMethodCode":{"role":"symbol","title":"iMojeSDKError.emptyPaymentMethodCode","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"emptyPaymentMethodCode"}],"abstract":[{"type":"text","text":"Raise when service has empty payment method code"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError\/emptyPaymentMethodCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"iMojeSDKErrorEmptyPaymentMethodCode"}],"url":"\/documentation\/imojesdk\/imojesdkerror\/emptypaymentmethodcode"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK":{"role":"collection","title":"iMojeSDK","abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/iMojeSDKError":{"role":"symbol","title":"iMojeSDKError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"iMojeSDKError"}],"abstract":[{"type":"text","text":"iMojeSDKError"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"iMojeSDKError"}],"url":"\/documentation\/imojesdk\/imojesdkerror"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"iMojeSDKErrorEmptyPaymentMethodCode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"iMojeSDKErrorEmptyPaymentMethodCode"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"iMojeSDKErrorEmptyPaymentMethodCode"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1iMojeSDKError~1emptyPaymentMethodCode\/title","value":"iMojeSDKErrorEmptyPaymentMethodCode"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1iMojeSDKError~1emptyPaymentMethodCode\/fragments","value":[{"kind":"identifier","text":"iMojeSDKErrorEmptyPaymentMethodCode"}]},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1iMojeSDKError\/title","value":"iMojeSDKError"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1iMojeSDKError\/fragments","value":[{"kind":"identifier","text":"iMojeSDKError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}