{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"missingServiceId"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/imojesdk\/imojesdkerror\/missingserviceid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/imojesdk\/imojesdkerror\/missingserviceid"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError\/missingServiceId","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Raise when user not set service id for sdk"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"missingServiceId"}],"title":"iMojeSDKError.missingServiceId","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@iMojeSDK@E@iMojeSDKError@iMojeSDKErrorMissingServiceId","modules":[{"name":"iMojeSDK"}],"navigatorTitle":[{"kind":"identifier","text":"iMojeSDKErrorMissingServiceId"}]},"hierarchy":{"paths":[["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError"]]},"references":{"doc://pl.netizens.imojesdk/documentation/iMojeSDK/iMojeSDKError/missingServiceId":{"role":"symbol","title":"iMojeSDKError.missingServiceId","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"missingServiceId"}],"abstract":[{"type":"text","text":"Raise when user not set service id for sdk"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError\/missingServiceId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"iMojeSDKErrorMissingServiceId"}],"url":"\/documentation\/imojesdk\/imojesdkerror\/missingserviceid"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/iMojeSDKError":{"role":"symbol","title":"iMojeSDKError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"iMojeSDKError"}],"abstract":[{"type":"text","text":"iMojeSDKError"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"iMojeSDKError"}],"url":"\/documentation\/imojesdk\/imojesdkerror"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK":{"role":"collection","title":"iMojeSDK","abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"iMojeSDKErrorMissingServiceId"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"iMojeSDKErrorMissingServiceId"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"iMojeSDKErrorMissingServiceId"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1iMojeSDKError~1missingServiceId\/title","value":"iMojeSDKErrorMissingServiceId"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1iMojeSDKError~1missingServiceId\/fragments","value":[{"kind":"identifier","text":"iMojeSDKErrorMissingServiceId"}]},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1iMojeSDKError\/title","value":"iMojeSDKError"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1iMojeSDKError\/fragments","value":[{"kind":"identifier","text":"iMojeSDKError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}