{"variants":[{"paths":["\/documentation\/imojesdk"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/imojesdk"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK","interfaceLanguage":"swift"},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGApplePayHandler","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGBank","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGBankViewController","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGChosePaymentMethodView","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGChosePaymentViewController","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGConfirmView","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGConfirmViewController","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGPaymentMethodView","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGPoweredView","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGWebView","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGWebViewController","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/PaymentMethodCodeViewCell","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMoje"]},{"title":"Structures","identifiers":["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGApplePayResult","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGApplePayTransaction","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGConfirm","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGPaymentMethod","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGSummaryItemApplePay","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/WalletApplePay"]},{"title":"Type Aliases","identifiers":["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/ChosePaymentMethodViewItemSelected","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/ConfirmViewCallback"]},{"title":"Enumerations","identifiers":["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGFontStyle","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGPaymentMethodCodeType","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGPaymentMethodImage","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGPaymentMethodType","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGPaymentStandardMethodImage","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGWebViewContent","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/SDKStandardLanguageType","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError"]}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"iMojeSDK","title":"iMojeSDK","symbolKind":"module","role":"collection","modules":[{"name":"iMojeSDK"}]},"hierarchy":{"paths":[[]]},"references":{"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGPaymentMethod":{"role":"symbol","title":"INGPaymentMethod","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGPaymentMethod"}],"abstract":[{"type":"text","text":"Payment method"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGPaymentMethod","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"INGPaymentMethod"}],"url":"\/documentation\/imojesdk\/ingpaymentmethod"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGPaymentMethodType":{"role":"symbol","title":"INGPaymentMethodType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGPaymentMethodType"}],"abstract":[{"type":"text","text":"Payment method type "},{"type":"text","text":" "},{"type":"text","text":"See more: https:\/\/data.imoje.pl\/docs\/en\/api-transaction_en.pdf#page=14"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGPaymentMethodType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"INGPaymentMethodType"}],"url":"\/documentation\/imojesdk\/ingpaymentmethodtype"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGBank":{"role":"symbol","title":"INGBank","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGBank"}],"abstract":[{"type":"text","text":":nodoc:"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGBank","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"INGBank"}],"url":"\/documentation\/imojesdk\/ingbank"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/iMojeSDKVersionNumber":{"role":"symbol","title":"iMojeSDKVersionNumber","fragments":[{"kind":"identifier","text":"iMojeSDKVersionNumber"}],"abstract":[{"type":"text","text":"Project version number for iMojeSDK."}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKVersionNumber","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk\/imojesdkversionnumber"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGApplePayResult":{"role":"symbol","title":"INGApplePayResult","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGApplePayResult"}],"abstract":[{"type":"text","text":"Apple pay result object "}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGApplePayResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"INGApplePayResult"}],"url":"\/documentation\/imojesdk\/ingapplepayresult"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/ConfirmViewCallback":{"role":"symbol","title":"ConfirmViewCallback","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConfirmViewCallback"}],"abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/ConfirmViewCallback","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConfirmViewCallback"}],"url":"\/documentation\/imojesdk\/confirmviewcallback"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGBankViewController":{"role":"symbol","title":"INGBankViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGBankViewController"}],"abstract":[{"type":"text","text":"View Controller that allows user chooses bank method that he want to payment with"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGBankViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"INGBankViewController"}],"url":"\/documentation\/imojesdk\/ingbankviewcontroller"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGFontStyle":{"role":"symbol","title":"INGFontStyle","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGFontStyle"}],"abstract":[{"type":"text","text":"Font that provided by ING-SDK"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGFontStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"INGFontStyle"}],"url":"\/documentation\/imojesdk\/ingfontstyle"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGPoweredView":{"role":"symbol","title":"INGPoweredView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGPoweredView"}],"abstract":[{"type":"text","text":"View for ING powered view"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGPoweredView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"INGPoweredView"}],"url":"\/documentation\/imojesdk\/ingpoweredview"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGSummaryItemApplePay":{"role":"symbol","title":"INGSummaryItemApplePay","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGSummaryItemApplePay"}],"abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGSummaryItemApplePay","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"INGSummaryItemApplePay"}],"url":"\/documentation\/imojesdk\/ingsummaryitemapplepay"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/iMojeSDKErrorDomain":{"role":"symbol","title":"iMojeSDKErrorDomain","fragments":[{"kind":"identifier","text":"iMojeSDKErrorDomain"}],"abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKErrorDomain","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk\/imojesdkerrordomain"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/ChosePaymentMethodViewItemSelected":{"role":"symbol","title":"ChosePaymentMethodViewItemSelected","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChosePaymentMethodViewItemSelected"}],"abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/ChosePaymentMethodViewItemSelected","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChosePaymentMethodViewItemSelected"}],"url":"\/documentation\/imojesdk\/chosepaymentmethodviewitemselected"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGPaymentMethodCodeType":{"role":"symbol","title":"INGPaymentMethodCodeType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGPaymentMethodCodeType"}],"abstract":[{"type":"text","text":"Payment method code type "},{"type":"text","text":" "},{"type":"text","text":"See more: https:\/\/data.imoje.pl\/docs\/en\/api-transaction_en.pdf#page=14"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGPaymentMethodCodeType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"INGPaymentMethodCodeType"}],"url":"\/documentation\/imojesdk\/ingpaymentmethodcodetype"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGConfirmViewController":{"role":"symbol","title":"INGConfirmViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGConfirmViewController"}],"abstract":[{"type":"text","text":"View Controller that containts regulamins that user has accept"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGConfirmViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"INGConfirmViewController"}],"url":"\/documentation\/imojesdk\/ingconfirmviewcontroller"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGApplePayHandler":{"role":"symbol","title":"INGApplePayHandler","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGApplePayHandler"}],"abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGApplePayHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"INGApplePayHandler"}],"url":"\/documentation\/imojesdk\/ingapplepayhandler"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGWebViewController":{"role":"symbol","title":"INGWebViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGWebViewController"}],"abstract":[{"type":"text","text":"View Controller that shows web contents"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGWebViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"INGWebViewController"}],"url":"\/documentation\/imojesdk\/ingwebviewcontroller"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGConfirmView":{"role":"symbol","title":"INGConfirmView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGConfirmView"}],"abstract":[{"type":"text","text":"View that containts regulamins that user has accept"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGConfirmView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"INGConfirmView"}],"url":"\/documentation\/imojesdk\/ingconfirmview"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGConfirm":{"role":"symbol","title":"INGConfirm","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGConfirm"}],"abstract":[{"type":"text","text":"Input for "},{"type":"codeVoice","code":"INGConfirmView"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGConfirm","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"INGConfirm"}],"url":"\/documentation\/imojesdk\/ingconfirm"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGPaymentMethodView":{"role":"symbol","title":"INGPaymentMethodView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGPaymentMethodView"}],"abstract":[{"type":"text","text":"List payment method code view"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGPaymentMethodView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"INGPaymentMethodView"}],"url":"\/documentation\/imojesdk\/ingpaymentmethodview"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGApplePayTransaction":{"role":"symbol","title":"INGApplePayTransaction","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGApplePayTransaction"}],"abstract":[{"type":"text","text":"An object that represents a request for payment, including information about payment processing capabilities, the payment amount, and contact information."}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGApplePayTransaction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"INGApplePayTransaction"}],"url":"\/documentation\/imojesdk\/ingapplepaytransaction"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGChosePaymentMethodView":{"role":"symbol","title":"INGChosePaymentMethodView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGChosePaymentMethodView"}],"abstract":[{"type":"text","text":"View  that allows user chooses payment method that he want to payment with"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGChosePaymentMethodView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"INGChosePaymentMethodView"}],"url":"\/documentation\/imojesdk\/ingchosepaymentmethodview"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGPaymentMethodImage":{"role":"symbol","title":"INGPaymentMethodImage","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGPaymentMethodImage"}],"abstract":[{"type":"text","text":"Input image for method "},{"type":"codeVoice","code":"INGPaymentMethod.init(id:image:name:details)"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGPaymentMethodImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"INGPaymentMethodImage"}],"url":"\/documentation\/imojesdk\/ingpaymentmethodimage"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/iMoje":{"role":"symbol","title":"iMoje","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"iMoje"}],"abstract":[{"type":"text","text":"iMojeSDK"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMoje","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"iMoje"}],"url":"\/documentation\/imojesdk\/imoje"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGPaymentStandardMethodImage":{"role":"symbol","title":"INGPaymentStandardMethodImage","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGPaymentStandardMethodImage"}],"abstract":[{"type":"text","text":"Standard Images for method "},{"type":"codeVoice","code":"INGPaymentMethodImage.standard(type)"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGPaymentStandardMethodImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"INGPaymentStandardMethodImage"}],"url":"\/documentation\/imojesdk\/ingpaymentstandardmethodimage"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK":{"role":"collection","title":"iMojeSDK","abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/SDKStandardLanguageType":{"role":"symbol","title":"SDKStandardLanguageType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDKStandardLanguageType"}],"abstract":[{"type":"text","text":"Language type for SDK "}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/SDKStandardLanguageType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDKStandardLanguageType"}],"url":"\/documentation\/imojesdk\/sdkstandardlanguagetype"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGWebViewContent":{"role":"symbol","title":"INGWebViewContent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGWebViewContent"}],"abstract":[{"type":"text","text":"Input for "},{"type":"codeVoice","code":"INGWebView"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGWebViewContent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"INGWebViewContent"}],"url":"\/documentation\/imojesdk\/ingwebviewcontent"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/PaymentMethodCodeViewCell":{"role":"symbol","title":"PaymentMethodCodeViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentMethodCodeViewCell"}],"abstract":[{"type":"text","text":"Payment method code item view"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/PaymentMethodCodeViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PaymentMethodCodeViewCell"}],"url":"\/documentation\/imojesdk\/paymentmethodcodeviewcell"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/iMojeSDKVersionString":{"role":"symbol","title":"iMojeSDKVersionString","fragments":[{"kind":"identifier","text":"iMojeSDKVersionString"}],"abstract":[{"type":"text","text":"Project version string for iMojeSDK."}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKVersionString","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk\/imojesdkversionstring"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGChosePaymentViewController":{"role":"symbol","title":"INGChosePaymentViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGChosePaymentViewController"}],"abstract":[{"type":"text","text":"View Controller that allows user chooses payment method that he want to payment with"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGChosePaymentViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"INGChosePaymentViewController"}],"url":"\/documentation\/imojesdk\/ingchosepaymentviewcontroller"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGWebView":{"role":"symbol","title":"INGWebView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGWebView"}],"abstract":[{"type":"text","text":"View  that shows web contents"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGWebView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"INGWebView"}],"url":"\/documentation\/imojesdk\/ingwebview"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/iMojeSDKError":{"role":"symbol","title":"iMojeSDKError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"iMojeSDKError"}],"abstract":[{"type":"text","text":"iMojeSDKError"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"iMojeSDKError"}],"url":"\/documentation\/imojesdk\/imojesdkerror"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/WalletApplePay":{"role":"symbol","title":"WalletApplePay","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"WalletApplePay"}],"abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/WalletApplePay","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WalletApplePay"}],"url":"\/documentation\/imojesdk\/walletapplepay"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Classes","identifiers":["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGApplePayHandler","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGBank","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGBankViewController","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGChosePaymentMethodView","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGChosePaymentViewController","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGConfirmView","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGConfirmViewController","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGPaymentMethodView","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGPoweredView","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGWebView","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGWebViewController","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/PaymentMethodCodeViewCell","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMoje"]},{"title":"Variables","identifiers":["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKErrorDomain","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKVersionNumber","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKVersionString"]},{"title":"Enumerations","identifiers":["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGBank\/title","value":"INGBank"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGBank\/fragments","value":[{"kind":"identifier","text":"INGBank"}]},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGBankViewController\/title","value":"INGBankViewController"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGBankViewController\/fragments","value":[{"kind":"identifier","text":"INGBankViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGPoweredView\/title","value":"INGPoweredView"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGPoweredView\/fragments","value":[{"kind":"identifier","text":"INGPoweredView"}]},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGConfirmViewController\/title","value":"INGConfirmViewController"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGConfirmViewController\/fragments","value":[{"kind":"identifier","text":"INGConfirmViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGApplePayHandler\/title","value":"INGApplePayHandler"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGApplePayHandler\/fragments","value":[{"kind":"identifier","text":"INGApplePayHandler"}]},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGWebViewController\/title","value":"INGWebViewController"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGWebViewController\/fragments","value":[{"kind":"identifier","text":"INGWebViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGConfirmView\/title","value":"INGConfirmView"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGConfirmView\/fragments","value":[{"kind":"identifier","text":"INGConfirmView"}]},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGPaymentMethodView\/title","value":"INGPaymentMethodView"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGPaymentMethodView\/fragments","value":[{"kind":"identifier","text":"INGPaymentMethodView"}]},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGChosePaymentMethodView\/title","value":"INGChosePaymentMethodView"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGChosePaymentMethodView\/fragments","value":[{"kind":"identifier","text":"INGChosePaymentMethodView"}]},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1iMoje\/title","value":"iMoje"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1iMoje\/fragments","value":[{"kind":"identifier","text":"iMoje"}]},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1PaymentMethodCodeViewCell\/title","value":"PaymentMethodCodeViewCell"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1PaymentMethodCodeViewCell\/fragments","value":[{"kind":"identifier","text":"PaymentMethodCodeViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGChosePaymentViewController\/title","value":"INGChosePaymentViewController"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGChosePaymentViewController\/fragments","value":[{"kind":"identifier","text":"INGChosePaymentViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGWebView\/title","value":"INGWebView"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGWebView\/fragments","value":[{"kind":"identifier","text":"INGWebView"}]},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1iMojeSDKError\/title","value":"iMojeSDKError"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1iMojeSDKError\/fragments","value":[{"kind":"identifier","text":"iMojeSDKError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}