{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onFailure"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError","preciseIdentifier":"c:@M@iMojeSDK@E@iMojeSDKError","text":"iMojeSDKError"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/imojesdk\/ingapplepayhandler\/onfailure"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGApplePayHandler\/onFailure","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when payment failed"}],"kind":"symbol","metadata":{"role":"symbol","title":"onFailure","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onFailure"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"iMojeSDKError","preciseIdentifier":"c:@M@iMojeSDK@E@iMojeSDKError"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"symbolKind":"property","externalID":"s:8iMojeSDK18INGApplePayHandlerC9onFailureyAA01iA8SDKErrorOcSgvp","modules":[{"name":"iMojeSDK"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"11.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGApplePayHandler"]]},"references":{"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGApplePayHandler/onFailure":{"role":"symbol","title":"onFailure","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onFailure"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"iMojeSDKError","preciseIdentifier":"c:@M@iMojeSDK@E@iMojeSDKError"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"Called when payment failed"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGApplePayHandler\/onFailure","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk\/ingapplepayhandler\/onfailure"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGApplePayHandler":{"role":"symbol","title":"INGApplePayHandler","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGApplePayHandler"}],"abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGApplePayHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"INGApplePayHandler"}],"url":"\/documentation\/imojesdk\/ingapplepayhandler"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK":{"role":"collection","title":"iMojeSDK","abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/iMojeSDKError":{"role":"symbol","title":"iMojeSDKError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"iMojeSDKError"}],"abstract":[{"type":"text","text":"iMojeSDKError"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"iMojeSDKError"}],"url":"\/documentation\/imojesdk\/imojesdkerror"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGApplePayHandler\/title","value":"INGApplePayHandler"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGApplePayHandler\/fragments","value":[{"kind":"identifier","text":"INGApplePayHandler"}]},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1iMojeSDKError\/title","value":"iMojeSDKError"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1iMojeSDKError\/fragments","value":[{"kind":"identifier","text":"iMojeSDKError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}