{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentAuthorizationViewControllerDidFinish"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PKPaymentAuthorizationViewController","preciseIdentifier":"c:objc(cs)PKPaymentAuthorizationViewController"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/imojesdk\/ingapplepayhandler\/paymentauthorizationviewcontrollerdidfinish(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/imojesdk\/ingapplepayhandler\/paymentauthorizationviewcontrollerdidfinish(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGApplePayHandler\/paymentAuthorizationViewControllerDidFinish(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"PKPaymentAuthorizationViewControllerDelegate.paymentAuthorizationViewControllerDidFinish(_:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"modules":[{"name":"iMojeSDK"}],"navigatorTitle":[{"kind":"identifier","text":"paymentAuthorizationViewControllerDidFinish:"}],"role":"symbol","title":"paymentAuthorizationViewControllerDidFinish(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentAuthorizationViewControllerDidFinish"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PKPaymentAuthorizationViewController","preciseIdentifier":"c:objc(cs)PKPaymentAuthorizationViewController"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@CM@iMojeSDK@objc(cs)INGApplePayHandler(im)paymentAuthorizationViewControllerDidFinish:","extendedModule":"iMojeSDK","platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"11.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGApplePayHandler","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGApplePayHandler\/PKPaymentAuthorizationViewControllerDelegate-Implementations"]]},"references":{"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGApplePayHandler/paymentAuthorizationViewControllerDidFinish(_:)":{"role":"symbol","title":"paymentAuthorizationViewControllerDidFinish(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentAuthorizationViewControllerDidFinish"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PKPaymentAuthorizationViewController","preciseIdentifier":"c:objc(cs)PKPaymentAuthorizationViewController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGApplePayHandler\/paymentAuthorizationViewControllerDidFinish(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"paymentAuthorizationViewControllerDidFinish:"}],"url":"\/documentation\/imojesdk\/ingapplepayhandler\/paymentauthorizationviewcontrollerdidfinish(_:)"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGApplePayHandler/PKPaymentAuthorizationViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"PKPaymentAuthorizationViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGApplePayHandler\/PKPaymentAuthorizationViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/imojesdk\/ingapplepayhandler\/pkpaymentauthorizationviewcontrollerdelegate-implementations"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK":{"role":"collection","title":"iMojeSDK","abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGApplePayHandler":{"role":"symbol","title":"INGApplePayHandler","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGApplePayHandler"}],"abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGApplePayHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"INGApplePayHandler"}],"url":"\/documentation\/imojesdk\/ingapplepayhandler"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"paymentAuthorizationViewControllerDidFinish:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentAuthorizationViewControllerDidFinish:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"paymentAuthorizationViewControllerDidFinish:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PKPaymentAuthorizationViewController","preciseIdentifier":"c:objc(cs)PKPaymentAuthorizationViewController"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"controller"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGApplePayHandler~1paymentAuthorizationViewControllerDidFinish(_:)\/title","value":"paymentAuthorizationViewControllerDidFinish:"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGApplePayHandler~1paymentAuthorizationViewControllerDidFinish(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentAuthorizationViewControllerDidFinish:"}]},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGApplePayHandler\/title","value":"INGApplePayHandler"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGApplePayHandler\/fragments","value":[{"kind":"identifier","text":"INGApplePayHandler"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}