{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentAuthorizationViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PKPaymentAuthorizationViewController","preciseIdentifier":"c:objc(cs)PKPaymentAuthorizationViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didAuthorizePayment"},{"kind":"text","text":" "},{"kind":"internalParam","text":"payment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PKPayment","preciseIdentifier":"c:objc(cs)PKPayment"},{"kind":"text","text":", "},{"kind":"externalParam","text":"handler"},{"kind":"text","text":" "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","text":"PKPaymentAuthorizationResult","preciseIdentifier":"c:objc(cs)PKPaymentAuthorizationResult"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/imojesdk\/ingapplepayhandler\/paymentauthorizationviewcontroller(_:didauthorizepayment:handler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/imojesdk\/ingapplepayhandler\/paymentauthorizationviewcontroller(_:didauthorizepayment:handler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGApplePayHandler\/paymentAuthorizationViewController(_:didAuthorizePayment:handler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"PKPaymentAuthorizationViewControllerDelegate.paymentAuthorizationViewController(_:didAuthorizePayment:handler:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"paymentAuthorizationViewController:didAuthorizePayment:handler:"}],"role":"symbol","title":"paymentAuthorizationViewController(_:didAuthorizePayment:handler:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentAuthorizationViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PKPaymentAuthorizationViewController","preciseIdentifier":"c:objc(cs)PKPaymentAuthorizationViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didAuthorizePayment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PKPayment","preciseIdentifier":"c:objc(cs)PKPayment"},{"kind":"text","text":", "},{"kind":"externalParam","text":"handler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"PKPaymentAuthorizationResult","preciseIdentifier":"c:objc(cs)PKPaymentAuthorizationResult"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@CM@iMojeSDK@objc(cs)INGApplePayHandler(im)paymentAuthorizationViewController:didAuthorizePayment:handler:","modules":[{"name":"iMojeSDK"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"11.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGApplePayHandler","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGApplePayHandler\/PKPaymentAuthorizationViewControllerDelegate-Implementations"]]},"references":{"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGApplePayHandler/paymentAuthorizationViewController(_:didAuthorizePayment:handler:)":{"role":"symbol","title":"paymentAuthorizationViewController(_:didAuthorizePayment:handler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentAuthorizationViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PKPaymentAuthorizationViewController","preciseIdentifier":"c:objc(cs)PKPaymentAuthorizationViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didAuthorizePayment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PKPayment","preciseIdentifier":"c:objc(cs)PKPayment"},{"kind":"text","text":", "},{"kind":"externalParam","text":"handler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"PKPaymentAuthorizationResult","preciseIdentifier":"c:objc(cs)PKPaymentAuthorizationResult"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGApplePayHandler\/paymentAuthorizationViewController(_:didAuthorizePayment:handler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"paymentAuthorizationViewController:didAuthorizePayment:handler:"}],"url":"\/documentation\/imojesdk\/ingapplepayhandler\/paymentauthorizationviewcontroller(_:didauthorizepayment:handler:)"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK":{"role":"collection","title":"iMojeSDK","abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGApplePayHandler":{"role":"symbol","title":"INGApplePayHandler","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGApplePayHandler"}],"abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGApplePayHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"INGApplePayHandler"}],"url":"\/documentation\/imojesdk\/ingapplepayhandler"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGApplePayHandler/PKPaymentAuthorizationViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"PKPaymentAuthorizationViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGApplePayHandler\/PKPaymentAuthorizationViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/imojesdk\/ingapplepayhandler\/pkpaymentauthorizationviewcontrollerdelegate-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"paymentAuthorizationViewController:didAuthorizePayment:handler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentAuthorizationViewController:didAuthorizePayment:handler:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"paymentAuthorizationViewController:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PKPaymentAuthorizationViewController","preciseIdentifier":"c:objc(cs)PKPaymentAuthorizationViewController"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"controller"},{"kind":"text","text":" "},{"kind":"identifier","text":"didAuthorizePayment:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PKPayment","preciseIdentifier":"c:objc(cs)PKPayment"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"payment"},{"kind":"text","text":" "},{"kind":"identifier","text":"handler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(PKPaymentAuthorizationResult *)","preciseIdentifier":"c:BFv(#*$objc(cs)PKPaymentAuthorizationResult)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGApplePayHandler~1paymentAuthorizationViewController(_:didAuthorizePayment:handler:)\/title","value":"paymentAuthorizationViewController:didAuthorizePayment:handler:"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGApplePayHandler~1paymentAuthorizationViewController(_:didAuthorizePayment:handler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentAuthorizationViewController:didAuthorizePayment:handler:"}]},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGApplePayHandler\/title","value":"INGApplePayHandler"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGApplePayHandler\/fragments","value":[{"kind":"identifier","text":"INGApplePayHandler"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}