{"variants":[{"paths":["\/documentation\/imojesdk\/ingapplepayhandler\/pkpaymentauthorizationviewcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/imojesdk\/ingapplepayhandler\/pkpaymentauthorizationviewcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGApplePayHandler\/PKPaymentAuthorizationViewControllerDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGApplePayHandler\/paymentAuthorizationViewController(_:didAuthorizePayment:handler:)","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGApplePayHandler\/paymentAuthorizationViewControllerDidFinish(_:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"iMojeSDK"}],"role":"collectionGroup","title":"PKPaymentAuthorizationViewControllerDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGApplePayHandler"]]},"references":{"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGApplePayHandler":{"role":"symbol","title":"INGApplePayHandler","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGApplePayHandler"}],"abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGApplePayHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"INGApplePayHandler"}],"url":"\/documentation\/imojesdk\/ingapplepayhandler"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK":{"role":"collection","title":"iMojeSDK","abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGApplePayHandler/paymentAuthorizationViewControllerDidFinish(_:)":{"role":"symbol","title":"paymentAuthorizationViewControllerDidFinish(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentAuthorizationViewControllerDidFinish"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PKPaymentAuthorizationViewController","preciseIdentifier":"c:objc(cs)PKPaymentAuthorizationViewController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGApplePayHandler\/paymentAuthorizationViewControllerDidFinish(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"paymentAuthorizationViewControllerDidFinish:"}],"url":"\/documentation\/imojesdk\/ingapplepayhandler\/paymentauthorizationviewcontrollerdidfinish(_:)"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGApplePayHandler/paymentAuthorizationViewController(_:didAuthorizePayment:handler:)":{"role":"symbol","title":"paymentAuthorizationViewController(_:didAuthorizePayment:handler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentAuthorizationViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PKPaymentAuthorizationViewController","preciseIdentifier":"c:objc(cs)PKPaymentAuthorizationViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didAuthorizePayment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PKPayment","preciseIdentifier":"c:objc(cs)PKPayment"},{"kind":"text","text":", "},{"kind":"externalParam","text":"handler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"PKPaymentAuthorizationResult","preciseIdentifier":"c:objc(cs)PKPaymentAuthorizationResult"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGApplePayHandler\/paymentAuthorizationViewController(_:didAuthorizePayment:handler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"paymentAuthorizationViewController:didAuthorizePayment:handler:"}],"url":"\/documentation\/imojesdk\/ingapplepayhandler\/paymentauthorizationviewcontroller(_:didauthorizepayment:handler:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGApplePayHandler\/paymentAuthorizationViewController(_:didAuthorizePayment:handler:)","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGApplePayHandler\/paymentAuthorizationViewControllerDidFinish(_:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGApplePayHandler\/title","value":"INGApplePayHandler"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGApplePayHandler\/fragments","value":[{"kind":"identifier","text":"INGApplePayHandler"}]},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGApplePayHandler~1paymentAuthorizationViewControllerDidFinish(_:)\/title","value":"paymentAuthorizationViewControllerDidFinish:"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGApplePayHandler~1paymentAuthorizationViewControllerDidFinish(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentAuthorizationViewControllerDidFinish:"}]},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGApplePayHandler~1paymentAuthorizationViewController(_:didAuthorizePayment:handler:)\/title","value":"paymentAuthorizationViewController:didAuthorizePayment:handler:"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGApplePayHandler~1paymentAuthorizationViewController(_:didAuthorizePayment:handler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentAuthorizationViewController:didAuthorizePayment:handler:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}