{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharedInstance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMoje","preciseIdentifier":"c:@M@iMojeSDK@objc(cs)iMoje","text":"iMoje"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/imojesdk\/imoje\/sharedinstance"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/imojesdk\/imoje\/sharedinstance"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMoje\/sharedInstance","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharedInstance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"iMoje","preciseIdentifier":"c:@M@iMojeSDK@objc(cs)iMoje"}],"title":"sharedInstance","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:@M@iMojeSDK@objc(cs)iMoje(cpy)sharedInstance","modules":[{"name":"iMojeSDK"}],"navigatorTitle":[{"kind":"identifier","text":"sharedInstance"}]},"hierarchy":{"paths":[["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMoje"]]},"references":{"doc://pl.netizens.imojesdk/documentation/iMojeSDK/iMoje/sharedInstance":{"role":"symbol","title":"sharedInstance","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharedInstance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"iMoje","preciseIdentifier":"c:@M@iMojeSDK@objc(cs)iMoje"}],"abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMoje\/sharedInstance","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sharedInstance"}],"url":"\/documentation\/imojesdk\/imoje\/sharedinstance"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK":{"role":"collection","title":"iMojeSDK","abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/iMoje":{"role":"symbol","title":"iMoje","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"iMoje"}],"abstract":[{"type":"text","text":"iMojeSDK"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMoje","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"iMoje"}],"url":"\/documentation\/imojesdk\/imoje"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"sharedInstance"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"sharedInstance"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMoje","preciseIdentifier":"c:@M@iMojeSDK@objc(cs)iMoje","text":"iMoje"},{"kind":"text","text":" * "},{"kind":"identifier","text":"sharedInstance"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1iMoje~1sharedInstance\/title","value":"sharedInstance"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1iMoje~1sharedInstance\/fragments","value":[{"kind":"identifier","text":"sharedInstance"}]},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1iMoje\/title","value":"iMoje"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1iMoje\/fragments","value":[{"kind":"identifier","text":"iMoje"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}