{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"dynamic"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"borderColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGColor","preciseIdentifier":"c:@T@CGColorRef"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/imojesdk\/paymentmethodcodeviewcell\/bordercolor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/imojesdk\/paymentmethodcodeviewcell\/bordercolor"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/PaymentMethodCodeViewCell\/borderColor","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"border color"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"borderColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGColor","preciseIdentifier":"c:@T@CGColorRef"}],"title":"borderColor","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@iMojeSDK@objc(cs)PaymentMethodCodeViewCell(py)borderColor","modules":[{"name":"iMojeSDK"}],"navigatorTitle":[{"kind":"identifier","text":"borderColor"}]},"hierarchy":{"paths":[["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/PaymentMethodCodeViewCell"]]},"references":{"doc://pl.netizens.imojesdk/documentation/iMojeSDK":{"role":"collection","title":"iMojeSDK","abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/PaymentMethodCodeViewCell":{"role":"symbol","title":"PaymentMethodCodeViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentMethodCodeViewCell"}],"abstract":[{"type":"text","text":"Payment method code item view"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/PaymentMethodCodeViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PaymentMethodCodeViewCell"}],"url":"\/documentation\/imojesdk\/paymentmethodcodeviewcell"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/PaymentMethodCodeViewCell/borderColor":{"role":"symbol","title":"borderColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"borderColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGColor","preciseIdentifier":"c:@T@CGColorRef"}],"abstract":[{"type":"text","text":"border color"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/PaymentMethodCodeViewCell\/borderColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"borderColor"}],"url":"\/documentation\/imojesdk\/paymentmethodcodeviewcell\/bordercolor"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"borderColor"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"borderColor"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"CGColor","preciseIdentifier":"c:@S@CGColor"},{"kind":"text","text":" * "},{"kind":"identifier","text":"borderColor"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1PaymentMethodCodeViewCell\/title","value":"PaymentMethodCodeViewCell"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1PaymentMethodCodeViewCell\/fragments","value":[{"kind":"identifier","text":"PaymentMethodCodeViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1PaymentMethodCodeViewCell~1borderColor\/title","value":"borderColor"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1PaymentMethodCodeViewCell~1borderColor\/fragments","value":[{"kind":"identifier","text":"borderColor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}