{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepareForReuse"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/imojesdk\/paymentmethodcodeviewcell\/prepareforreuse()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/imojesdk\/paymentmethodcodeviewcell\/prepareforreuse()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/PaymentMethodCodeViewCell\/prepareForReuse()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":":nodoc:"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepareForReuse"},{"kind":"text","text":"()"}],"title":"prepareForReuse()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@iMojeSDK@objc(cs)PaymentMethodCodeViewCell(im)prepareForReuse","modules":[{"name":"iMojeSDK"}],"navigatorTitle":[{"kind":"identifier","text":"prepareForReuse"}]},"hierarchy":{"paths":[["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/PaymentMethodCodeViewCell"]]},"references":{"doc://pl.netizens.imojesdk/documentation/iMojeSDK/PaymentMethodCodeViewCell/prepareForReuse()":{"role":"symbol","title":"prepareForReuse()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepareForReuse"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":":nodoc:"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/PaymentMethodCodeViewCell\/prepareForReuse()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"prepareForReuse"}],"url":"\/documentation\/imojesdk\/paymentmethodcodeviewcell\/prepareforreuse()"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/PaymentMethodCodeViewCell":{"role":"symbol","title":"PaymentMethodCodeViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentMethodCodeViewCell"}],"abstract":[{"type":"text","text":"Payment method code item view"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/PaymentMethodCodeViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PaymentMethodCodeViewCell"}],"url":"\/documentation\/imojesdk\/paymentmethodcodeviewcell"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK":{"role":"collection","title":"iMojeSDK","abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"prepareForReuse"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"prepareForReuse"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"prepareForReuse"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1PaymentMethodCodeViewCell~1prepareForReuse()\/title","value":"prepareForReuse"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1PaymentMethodCodeViewCell~1prepareForReuse()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"prepareForReuse"}]},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1PaymentMethodCodeViewCell\/title","value":"PaymentMethodCodeViewCell"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1PaymentMethodCodeViewCell\/fragments","value":[{"kind":"identifier","text":"PaymentMethodCodeViewCell"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}