{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bankSelected"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGBank","preciseIdentifier":"c:@M@iMojeSDK@objc(cs)INGBank","text":"INGBank"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/imojesdk\/ingbankviewcontroller\/bankselected"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGBankViewController\/bankSelected","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Call when user select bank"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bankSelected"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"INGBank","preciseIdentifier":"c:@M@iMojeSDK@objc(cs)INGBank"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"title":"bankSelected","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:8iMojeSDK21INGBankViewControllerC12bankSelectedyAA0C0CcSgvp","modules":[{"name":"iMojeSDK"}]},"hierarchy":{"paths":[["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGBankViewController"]]},"references":{"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGBankViewController":{"role":"symbol","title":"INGBankViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGBankViewController"}],"abstract":[{"type":"text","text":"View Controller that allows user chooses bank method that he want to payment with"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGBankViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"INGBankViewController"}],"url":"\/documentation\/imojesdk\/ingbankviewcontroller"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGBankViewController/bankSelected":{"role":"symbol","title":"bankSelected","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bankSelected"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"INGBank","preciseIdentifier":"c:@M@iMojeSDK@objc(cs)INGBank"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"Call when user select bank"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGBankViewController\/bankSelected","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk\/ingbankviewcontroller\/bankselected"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK":{"role":"collection","title":"iMojeSDK","abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGBank":{"role":"symbol","title":"INGBank","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGBank"}],"abstract":[{"type":"text","text":":nodoc:"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGBank","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"INGBank"}],"url":"\/documentation\/imojesdk\/ingbank"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGBankViewController\/title","value":"INGBankViewController"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGBankViewController\/fragments","value":[{"kind":"identifier","text":"INGBankViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGBank\/title","value":"INGBank"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGBank\/fragments","value":[{"kind":"identifier","text":"INGBank"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}