{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"webView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"decidePolicyFor"},{"kind":"text","text":" "},{"kind":"internalParam","text":"navigationAction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKNavigationAction","preciseIdentifier":"c:objc(cs)WKNavigationAction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"decisionHandler"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","text":"WKNavigationActionPolicy","preciseIdentifier":"c:@E@WKNavigationActionPolicy"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/imojesdk\/ingwebview\/webview(_:decidepolicyfor:decisionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/imojesdk\/ingwebview\/webview(_:decidepolicyfor:decisionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGWebView\/webView(_:decidePolicyFor:decisionHandler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"WKNavigationDelegate.webView(_:decidePolicyFor:decisionHandler:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"decidePolicyFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKNavigationAction","preciseIdentifier":"c:objc(cs)WKNavigationAction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"decisionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"WKNavigationActionPolicy","preciseIdentifier":"c:@E@WKNavigationActionPolicy"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"title":"webView(_:decidePolicyFor:decisionHandler:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@iMojeSDK@objc(cs)INGWebView(im)webView:decidePolicyForNavigationAction:decisionHandler:","modules":[{"name":"iMojeSDK"}],"navigatorTitle":[{"kind":"identifier","text":"webView:decidePolicyForNavigationAction:decisionHandler:"}]},"hierarchy":{"paths":[["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGWebView","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGWebView\/WKNavigationDelegate-Implementations"]]},"references":{"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGWebView":{"role":"symbol","title":"INGWebView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGWebView"}],"abstract":[{"type":"text","text":"View  that shows web contents"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGWebView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"INGWebView"}],"url":"\/documentation\/imojesdk\/ingwebview"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK":{"role":"collection","title":"iMojeSDK","abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGWebView/webView(_:decidePolicyFor:decisionHandler:)":{"role":"symbol","title":"webView(_:decidePolicyFor:decisionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"decidePolicyFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKNavigationAction","preciseIdentifier":"c:objc(cs)WKNavigationAction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"decisionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"WKNavigationActionPolicy","preciseIdentifier":"c:@E@WKNavigationActionPolicy"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGWebView\/webView(_:decidePolicyFor:decisionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"webView:decidePolicyForNavigationAction:decisionHandler:"}],"url":"\/documentation\/imojesdk\/ingwebview\/webview(_:decidepolicyfor:decisionhandler:)"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGWebView/WKNavigationDelegate-Implementations":{"role":"collectionGroup","title":"WKNavigationDelegate Implementations","abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGWebView\/WKNavigationDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/imojesdk\/ingwebview\/wknavigationdelegate-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"webView:decidePolicyForNavigationAction:decisionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"webView:decidePolicyForNavigationAction:decisionHandler:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"webView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"webView"},{"kind":"text","text":" "},{"kind":"identifier","text":"decidePolicyForNavigationAction:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WKNavigationAction","preciseIdentifier":"c:objc(cs)WKNavigationAction"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"navigationAction"},{"kind":"text","text":" "},{"kind":"identifier","text":"decisionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(enum WKNavigationActionPolicy)","preciseIdentifier":"c:BFv(#$@E@WKNavigationActionPolicy)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"decisionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGWebView\/title","value":"INGWebView"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGWebView\/fragments","value":[{"kind":"identifier","text":"INGWebView"}]},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGWebView~1webView(_:decidePolicyFor:decisionHandler:)\/title","value":"webView:decidePolicyForNavigationAction:decisionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGWebView~1webView(_:decidePolicyFor:decisionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"webView:decidePolicyForNavigationAction:decisionHandler:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}