{"variants":[{"paths":["\/documentation\/imojesdk\/ingwebview\/wknavigationdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/imojesdk\/ingwebview\/wknavigationdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGWebView\/WKNavigationDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGWebView\/webView(_:decidePolicyFor:decisionHandler:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"iMojeSDK"}],"role":"collectionGroup","title":"WKNavigationDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGWebView"]]},"references":{"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGWebView":{"role":"symbol","title":"INGWebView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGWebView"}],"abstract":[{"type":"text","text":"View  that shows web contents"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGWebView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"INGWebView"}],"url":"\/documentation\/imojesdk\/ingwebview"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK":{"role":"collection","title":"iMojeSDK","abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGWebView/webView(_:decidePolicyFor:decisionHandler:)":{"role":"symbol","title":"webView(_:decidePolicyFor:decisionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"decidePolicyFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKNavigationAction","preciseIdentifier":"c:objc(cs)WKNavigationAction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"decisionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"WKNavigationActionPolicy","preciseIdentifier":"c:@E@WKNavigationActionPolicy"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGWebView\/webView(_:decidePolicyFor:decisionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"webView:decidePolicyForNavigationAction:decisionHandler:"}],"url":"\/documentation\/imojesdk\/ingwebview\/webview(_:decidepolicyfor:decisionhandler:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGWebView\/webView(_:decidePolicyFor:decisionHandler:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGWebView\/title","value":"INGWebView"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGWebView\/fragments","value":[{"kind":"identifier","text":"INGWebView"}]},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGWebView~1webView(_:decidePolicyFor:decisionHandler:)\/title","value":"webView:decidePolicyForNavigationAction:decisionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGWebView~1webView(_:decidePolicyFor:decisionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"webView:decidePolicyForNavigationAction:decisionHandler:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}