{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"iMoje"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/imojesdk\/imoje"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/imojesdk\/imoje"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/pl.netizens.imojesdk\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/pl.netizens.imojesdk\/objc(pl)NSObject","doc:\/\/pl.netizens.imojesdk\/7RxSwift18ReactiveCompatibleP","doc:\/\/pl.netizens.imojesdk\/s7CVarArgP","doc:\/\/pl.netizens.imojesdk\/s28CustomDebugStringConvertibleP","doc:\/\/pl.netizens.imojesdk\/s23CustomStringConvertibleP","doc:\/\/pl.netizens.imojesdk\/SQ","doc:\/\/pl.netizens.imojesdk\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMoje","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"iMojeSDK"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"iMoje"}],"title":"iMoje","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@iMojeSDK@objc(cs)iMoje","modules":[{"name":"iMojeSDK"}],"navigatorTitle":[{"kind":"identifier","text":"iMoje"}]},"hierarchy":{"paths":[["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMoje\/setLanguage(language:)"]},{"title":"Type Properties","identifiers":["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMoje\/sharedInstance"]}],"references":{"doc://pl.netizens.imojesdk/documentation/iMojeSDK/iMoje":{"role":"symbol","title":"iMoje","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"iMoje"}],"abstract":[{"type":"text","text":"iMojeSDK"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMoje","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"iMoje"}],"url":"\/documentation\/imojesdk\/imoje"},"doc://pl.netizens.imojesdk/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/pl.netizens.imojesdk\/SQ"},"doc://pl.netizens.imojesdk/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/pl.netizens.imojesdk\/SH"},"doc://pl.netizens.imojesdk/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/pl.netizens.imojesdk\/s7CVarArgP"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/iMoje/sharedInstance":{"role":"symbol","title":"sharedInstance","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharedInstance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"iMoje","preciseIdentifier":"c:@M@iMojeSDK@objc(cs)iMoje"}],"abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMoje\/sharedInstance","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sharedInstance"}],"url":"\/documentation\/imojesdk\/imoje\/sharedinstance"},"doc://pl.netizens.imojesdk/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(cs)NSObject"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/iMoje/setLanguage(language:)":{"role":"symbol","title":"setLanguage(language:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setLanguage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"language"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDKStandardLanguageType","preciseIdentifier":"s:8iMojeSDK23SDKStandardLanguageTypeO"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Set sdk language"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMoje\/setLanguage(language:)","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk\/imoje\/setlanguage(language:)"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK":{"role":"collection","title":"iMojeSDK","abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk"},"doc://pl.netizens.imojesdk/7RxSwift18ReactiveCompatibleP":{"type":"unresolvable","title":"RxSwift.ReactiveCompatible","identifier":"doc:\/\/pl.netizens.imojesdk\/7RxSwift18ReactiveCompatibleP"},"doc://pl.netizens.imojesdk/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/pl.netizens.imojesdk\/s23CustomStringConvertibleP"},"doc://pl.netizens.imojesdk/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)NSObject"},"doc://pl.netizens.imojesdk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/pl.netizens.imojesdk\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"iMoje"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"iMoje"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"iMoje"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Type Properties","identifiers":["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMoje\/sharedInstance"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/pl.netizens.imojesdk\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"iMoje"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1iMoje\/title","value":"iMoje"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1iMoje\/fragments","value":[{"kind":"identifier","text":"iMoje"}]},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1iMoje~1sharedInstance\/title","value":"sharedInstance"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1iMoje~1sharedInstance\/fragments","value":[{"kind":"identifier","text":"sharedInstance"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}