{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"iMojeSDKError"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/imojesdk\/imojesdkerror"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/imojesdk\/imojesdkerror"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/pl.netizens.imojesdk\/10Foundation14LocalizedErrorP","doc:\/\/pl.netizens.imojesdk\/SQ","doc:\/\/pl.netizens.imojesdk\/s5ErrorP","doc:\/\/pl.netizens.imojesdk\/SH","doc:\/\/pl.netizens.imojesdk\/SY","doc:\/\/pl.netizens.imojesdk\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"iMojeSDKError"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"iMojeSDKError"}],"title":"iMojeSDKError","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@iMojeSDK@E@iMojeSDKError","modules":[{"name":"iMojeSDK"}],"navigatorTitle":[{"kind":"identifier","text":"iMojeSDKError"}]},"hierarchy":{"paths":[["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError\/applePayNotSupported","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError\/applePayUserCancelled","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError\/emptyPaymentMethodCode","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError\/inactiveService","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError\/missingBody","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError\/missingMerchantId","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError\/missingServiceId","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError\/unknown"]},{"title":"Initializers","identifiers":["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError\/Equatable-Implementations","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError\/Error-Implementations","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError\/LocalizedError-Implementations","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://pl.netizens.imojesdk/documentation/iMojeSDK/iMojeSDKError/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/imojesdk\/imojesdkerror\/rawrepresentable-implementations"},"doc://pl.netizens.imojesdk/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/pl.netizens.imojesdk\/s8SendableP"},"doc://pl.netizens.imojesdk/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/pl.netizens.imojesdk\/SH"},"doc://pl.netizens.imojesdk/10Foundation14LocalizedErrorP":{"type":"unresolvable","title":"Foundation.LocalizedError","identifier":"doc:\/\/pl.netizens.imojesdk\/10Foundation14LocalizedErrorP"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/iMojeSDKError/LocalizedError-Implementations":{"role":"collectionGroup","title":"LocalizedError Implementations","abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError\/LocalizedError-Implementations","kind":"article","type":"topic","url":"\/documentation\/imojesdk\/imojesdkerror\/localizederror-implementations"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK":{"role":"collection","title":"iMojeSDK","abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk"},"doc://pl.netizens.imojesdk/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/pl.netizens.imojesdk\/SQ"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/iMojeSDKError":{"role":"symbol","title":"iMojeSDKError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"iMojeSDKError"}],"abstract":[{"type":"text","text":"iMojeSDKError"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"iMojeSDKError"}],"url":"\/documentation\/imojesdk\/imojesdkerror"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/iMojeSDKError/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/imojesdk\/imojesdkerror\/equatable-implementations"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/iMojeSDKError/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk\/imojesdkerror\/init(rawvalue:)"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/iMojeSDKError/emptyPaymentMethodCode":{"role":"symbol","title":"iMojeSDKError.emptyPaymentMethodCode","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"emptyPaymentMethodCode"}],"abstract":[{"type":"text","text":"Raise when service has empty payment method code"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError\/emptyPaymentMethodCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"iMojeSDKErrorEmptyPaymentMethodCode"}],"url":"\/documentation\/imojesdk\/imojesdkerror\/emptypaymentmethodcode"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/iMojeSDKError/missingMerchantId":{"role":"symbol","title":"iMojeSDKError.missingMerchantId","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"missingMerchantId"}],"abstract":[{"type":"text","text":"Raise when user not set merchant id for sdk"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError\/missingMerchantId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"iMojeSDKErrorMissingMerchantId"}],"url":"\/documentation\/imojesdk\/imojesdkerror\/missingmerchantid"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/iMojeSDKError/missingServiceId":{"role":"symbol","title":"iMojeSDKError.missingServiceId","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"missingServiceId"}],"abstract":[{"type":"text","text":"Raise when user not set service id for sdk"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError\/missingServiceId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"iMojeSDKErrorMissingServiceId"}],"url":"\/documentation\/imojesdk\/imojesdkerror\/missingserviceid"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/iMojeSDKError/unknown":{"role":"symbol","title":"iMojeSDKError.unknown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"abstract":[{"type":"text","text":"Unknown error"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError\/unknown","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"iMojeSDKErrorUnknown"}],"url":"\/documentation\/imojesdk\/imojesdkerror\/unknown"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/iMojeSDKError/inactiveService":{"role":"symbol","title":"iMojeSDKError.inactiveService","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"inactiveService"}],"abstract":[{"type":"text","text":"Raise when service is inactive"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError\/inactiveService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"iMojeSDKErrorInactiveService"}],"url":"\/documentation\/imojesdk\/imojesdkerror\/inactiveservice"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/iMojeSDKError/applePayUserCancelled":{"role":"symbol","title":"iMojeSDKError.applePayUserCancelled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"applePayUserCancelled"}],"abstract":[{"type":"text","text":"Rise when user cancel apple payment"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError\/applePayUserCancelled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"iMojeSDKErrorApplePayUserCancelled"}],"url":"\/documentation\/imojesdk\/imojesdkerror\/applepayusercancelled"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/iMojeSDKError/missingBody":{"role":"symbol","title":"iMojeSDKError.missingBody","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"missingBody"}],"abstract":[{"type":"text","text":"Raise when request missing body payload"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError\/missingBody","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"iMojeSDKErrorMissingBody"}],"url":"\/documentation\/imojesdk\/imojesdkerror\/missingbody"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/iMojeSDKError/applePayNotSupported":{"role":"symbol","title":"iMojeSDKError.applePayNotSupported","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"applePayNotSupported"}],"abstract":[{"type":"text","text":"Rise when ApplePay is not supported"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError\/applePayNotSupported","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"iMojeSDKErrorApplePayNotSupported"}],"url":"\/documentation\/imojesdk\/imojesdkerror\/applepaynotsupported"},"doc://pl.netizens.imojesdk/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/pl.netizens.imojesdk\/SY"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/iMojeSDKError/Error-Implementations":{"role":"collectionGroup","title":"Error Implementations","abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError\/Error-Implementations","kind":"article","type":"topic","url":"\/documentation\/imojesdk\/imojesdkerror\/error-implementations"},"doc://pl.netizens.imojesdk/s5ErrorP":{"type":"unresolvable","title":"Swift.Error","identifier":"doc:\/\/pl.netizens.imojesdk\/s5ErrorP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"iMojeSDKError"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"iMojeSDKError"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"iMojeSDKError"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError\/applePayNotSupported","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError\/applePayUserCancelled","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError\/emptyPaymentMethodCode","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError\/inactiveService","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError\/missingBody","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError\/missingMerchantId","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError\/missingServiceId","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/iMojeSDKError\/unknown"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"iMojeSDKError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1iMojeSDKError\/title","value":"iMojeSDKError"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1iMojeSDKError\/fragments","value":[{"kind":"identifier","text":"iMojeSDKError"}]},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1iMojeSDKError~1emptyPaymentMethodCode\/title","value":"iMojeSDKErrorEmptyPaymentMethodCode"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1iMojeSDKError~1emptyPaymentMethodCode\/fragments","value":[{"kind":"identifier","text":"iMojeSDKErrorEmptyPaymentMethodCode"}]},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1iMojeSDKError~1missingMerchantId\/title","value":"iMojeSDKErrorMissingMerchantId"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1iMojeSDKError~1missingMerchantId\/fragments","value":[{"kind":"identifier","text":"iMojeSDKErrorMissingMerchantId"}]},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1iMojeSDKError~1missingServiceId\/title","value":"iMojeSDKErrorMissingServiceId"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1iMojeSDKError~1missingServiceId\/fragments","value":[{"kind":"identifier","text":"iMojeSDKErrorMissingServiceId"}]},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1iMojeSDKError~1unknown\/title","value":"iMojeSDKErrorUnknown"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1iMojeSDKError~1unknown\/fragments","value":[{"kind":"identifier","text":"iMojeSDKErrorUnknown"}]},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1iMojeSDKError~1inactiveService\/title","value":"iMojeSDKErrorInactiveService"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1iMojeSDKError~1inactiveService\/fragments","value":[{"kind":"identifier","text":"iMojeSDKErrorInactiveService"}]},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1iMojeSDKError~1applePayUserCancelled\/title","value":"iMojeSDKErrorApplePayUserCancelled"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1iMojeSDKError~1applePayUserCancelled\/fragments","value":[{"kind":"identifier","text":"iMojeSDKErrorApplePayUserCancelled"}]},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1iMojeSDKError~1missingBody\/title","value":"iMojeSDKErrorMissingBody"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1iMojeSDKError~1missingBody\/fragments","value":[{"kind":"identifier","text":"iMojeSDKErrorMissingBody"}]},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1iMojeSDKError~1applePayNotSupported\/title","value":"iMojeSDKErrorApplePayNotSupported"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1iMojeSDKError~1applePayNotSupported\/fragments","value":[{"kind":"identifier","text":"iMojeSDKErrorApplePayNotSupported"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}