{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGApplePayHandler"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/imojesdk\/ingapplepayhandler"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/imojesdk\/ingapplepayhandler"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/pl.netizens.imojesdk\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/pl.netizens.imojesdk\/objc(pl)NSObject","doc:\/\/pl.netizens.imojesdk\/objc(pl)PKPaymentAuthorizationViewControllerDelegate","doc:\/\/pl.netizens.imojesdk\/7RxSwift18ReactiveCompatibleP","doc:\/\/pl.netizens.imojesdk\/s7CVarArgP","doc:\/\/pl.netizens.imojesdk\/s28CustomDebugStringConvertibleP","doc:\/\/pl.netizens.imojesdk\/s23CustomStringConvertibleP","doc:\/\/pl.netizens.imojesdk\/SQ","doc:\/\/pl.netizens.imojesdk\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGApplePayHandler","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGApplePayHandler\/init(onSuccess:onFailure:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGApplePayHandler\/onFailure","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGApplePayHandler\/onSuccess"]},{"title":"Instance Methods","identifiers":["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGApplePayHandler\/purchase(in:with:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGApplePayHandler\/PKPaymentAuthorizationViewControllerDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"INGApplePayHandler"}],"role":"symbol","title":"INGApplePayHandler","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGApplePayHandler"}],"symbolKind":"class","externalID":"c:@M@iMojeSDK@objc(cs)INGApplePayHandler","modules":[{"name":"iMojeSDK"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"11.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK"]]},"references":{"doc://pl.netizens.imojesdk/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(cs)NSObject"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGApplePayHandler/purchase(in:with:)":{"role":"symbol","title":"purchase(in:with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"purchase"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"INGApplePayTransaction","preciseIdentifier":"s:8iMojeSDK22INGApplePayTransactionV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGApplePayHandler\/purchase(in:with:)","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk\/ingapplepayhandler\/purchase(in:with:)"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGApplePayHandler/init(onSuccess:onFailure:)":{"role":"symbol","title":"init(onSuccess:onFailure:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"onSuccess"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"INGApplePayResult","preciseIdentifier":"s:8iMojeSDK17INGApplePayResultV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"onFailure"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"iMojeSDKError","preciseIdentifier":"c:@M@iMojeSDK@E@iMojeSDKError"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGApplePayHandler\/init(onSuccess:onFailure:)","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk\/ingapplepayhandler\/init(onsuccess:onfailure:)"},"doc://pl.netizens.imojesdk/objc(pl)PKPaymentAuthorizationViewControllerDelegate":{"type":"unresolvable","title":"PassKit.PKPaymentAuthorizationViewControllerDelegate","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)PKPaymentAuthorizationViewControllerDelegate"},"doc://pl.netizens.imojesdk/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/pl.netizens.imojesdk\/s23CustomStringConvertibleP"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGApplePayHandler/onFailure":{"role":"symbol","title":"onFailure","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onFailure"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"iMojeSDKError","preciseIdentifier":"c:@M@iMojeSDK@E@iMojeSDKError"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"Called when payment failed"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGApplePayHandler\/onFailure","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk\/ingapplepayhandler\/onfailure"},"doc://pl.netizens.imojesdk/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)NSObject"},"doc://pl.netizens.imojesdk/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/pl.netizens.imojesdk\/SQ"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK":{"role":"collection","title":"iMojeSDK","abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk"},"doc://pl.netizens.imojesdk/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/pl.netizens.imojesdk\/s7CVarArgP"},"doc://pl.netizens.imojesdk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/pl.netizens.imojesdk\/s28CustomDebugStringConvertibleP"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGApplePayHandler":{"role":"symbol","title":"INGApplePayHandler","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGApplePayHandler"}],"abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGApplePayHandler","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"INGApplePayHandler"}],"url":"\/documentation\/imojesdk\/ingapplepayhandler"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGApplePayHandler/PKPaymentAuthorizationViewControllerDelegate-Implementations":{"role":"collectionGroup","title":"PKPaymentAuthorizationViewControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGApplePayHandler\/PKPaymentAuthorizationViewControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/imojesdk\/ingapplepayhandler\/pkpaymentauthorizationviewcontrollerdelegate-implementations"},"doc://pl.netizens.imojesdk/7RxSwift18ReactiveCompatibleP":{"type":"unresolvable","title":"RxSwift.ReactiveCompatible","identifier":"doc:\/\/pl.netizens.imojesdk\/7RxSwift18ReactiveCompatibleP"},"doc://pl.netizens.imojesdk/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/pl.netizens.imojesdk\/SH"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGApplePayHandler/onSuccess":{"role":"symbol","title":"onSuccess","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSuccess"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"INGApplePayResult","preciseIdentifier":"s:8iMojeSDK17INGApplePayResultV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"Called when the payment was successful"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGApplePayHandler\/onSuccess","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk\/ingapplepayhandler\/onsuccess"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"11.0","deprecated":false}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"INGApplePayHandler"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"INGApplePayHandler"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"INGApplePayHandler"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Default Implementations","identifiers":["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGApplePayHandler\/PKPaymentAuthorizationViewControllerDelegate-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/pl.netizens.imojesdk\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGApplePayHandler"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGApplePayHandler\/title","value":"INGApplePayHandler"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGApplePayHandler\/fragments","value":[{"kind":"identifier","text":"INGApplePayHandler"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}