{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGBank"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/imojesdk\/ingbank"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/imojesdk\/ingbank"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/pl.netizens.imojesdk\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/pl.netizens.imojesdk\/objc(pl)NSObject","doc:\/\/pl.netizens.imojesdk\/7RxSwift18ReactiveCompatibleP","doc:\/\/pl.netizens.imojesdk\/s7CVarArgP","doc:\/\/pl.netizens.imojesdk\/s28CustomDebugStringConvertibleP","doc:\/\/pl.netizens.imojesdk\/s23CustomStringConvertibleP","doc:\/\/pl.netizens.imojesdk\/SQ","doc:\/\/pl.netizens.imojesdk\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGBank","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":":nodoc:"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGBank"}],"title":"INGBank","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@iMojeSDK@objc(cs)INGBank","modules":[{"name":"iMojeSDK"}],"navigatorTitle":[{"kind":"identifier","text":"INGBank"}]},"hierarchy":{"paths":[["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGBank\/init(paymentMethod:paymentMethodCode:isActive:isOnline:currency:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGBank\/currency","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGBank\/descriptionField","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGBank\/isActive","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGBank\/isOnline","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGBank\/paymentMethod","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGBank\/paymentMethodCode"]}],"references":{"doc://pl.netizens.imojesdk/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(cs)NSObject"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGBank":{"role":"symbol","title":"INGBank","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGBank"}],"abstract":[{"type":"text","text":":nodoc:"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGBank","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"INGBank"}],"url":"\/documentation\/imojesdk\/ingbank"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGBank/currency":{"role":"symbol","title":"currency","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currency"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGBank\/currency","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk\/ingbank\/currency"},"doc://pl.netizens.imojesdk/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/pl.netizens.imojesdk\/SQ"},"doc://pl.netizens.imojesdk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/pl.netizens.imojesdk\/s28CustomDebugStringConvertibleP"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGBank/descriptionField":{"role":"symbol","title":"descriptionField","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"descriptionField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGBank\/descriptionField","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk\/ingbank\/descriptionfield"},"doc://pl.netizens.imojesdk/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/pl.netizens.imojesdk\/s7CVarArgP"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGBank/paymentMethod":{"role":"symbol","title":"paymentMethod","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"INGPaymentMethodType","preciseIdentifier":"s:8iMojeSDK20INGPaymentMethodTypeO"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGBank\/paymentMethod","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk\/ingbank\/paymentmethod"},"doc://pl.netizens.imojesdk/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)NSObject"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGBank/isActive":{"role":"symbol","title":"isActive","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isActive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGBank\/isActive","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk\/ingbank\/isactive"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK":{"role":"collection","title":"iMojeSDK","abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGBank/isOnline":{"role":"symbol","title":"isOnline","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isOnline"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGBank\/isOnline","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk\/ingbank\/isonline"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGBank/init(paymentMethod:paymentMethodCode:isActive:isOnline:currency:)":{"role":"symbol","title":"init(paymentMethod:paymentMethodCode:isActive:isOnline:currency:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"paymentMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"INGPaymentMethodType","preciseIdentifier":"s:8iMojeSDK20INGPaymentMethodTypeO"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"paymentMethodCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"INGPaymentMethodCodeType","preciseIdentifier":"s:8iMojeSDK24INGPaymentMethodCodeTypeO"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"isActive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"isOnline"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"currency"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGBank\/init(paymentMethod:paymentMethodCode:isActive:isOnline:currency:)","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk\/ingbank\/init(paymentmethod:paymentmethodcode:isactive:isonline:currency:)"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGBank/paymentMethodCode":{"role":"symbol","title":"paymentMethodCode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentMethodCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"INGPaymentMethodCodeType","preciseIdentifier":"s:8iMojeSDK24INGPaymentMethodCodeTypeO"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGBank\/paymentMethodCode","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk\/ingbank\/paymentmethodcode"},"doc://pl.netizens.imojesdk/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/pl.netizens.imojesdk\/s23CustomStringConvertibleP"},"doc://pl.netizens.imojesdk/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/pl.netizens.imojesdk\/SH"},"doc://pl.netizens.imojesdk/7RxSwift18ReactiveCompatibleP":{"type":"unresolvable","title":"RxSwift.ReactiveCompatible","identifier":"doc:\/\/pl.netizens.imojesdk\/7RxSwift18ReactiveCompatibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"INGBank"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"INGBank"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"INGBank"}]},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/pl.netizens.imojesdk\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGBank"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGBank\/title","value":"INGBank"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGBank\/fragments","value":[{"kind":"identifier","text":"INGBank"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}