{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGBankViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/imojesdk\/ingbankviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/imojesdk\/ingbankviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/pl.netizens.imojesdk\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/pl.netizens.imojesdk\/objc(pl)NSCoding","doc:\/\/pl.netizens.imojesdk\/objc(pl)NSExtensionRequestHandling","doc:\/\/pl.netizens.imojesdk\/objc(pl)NSObject","doc:\/\/pl.netizens.imojesdk\/7RxSwift18ReactiveCompatibleP","doc:\/\/pl.netizens.imojesdk\/s7CVarArgP","doc:\/\/pl.netizens.imojesdk\/s28CustomDebugStringConvertibleP","doc:\/\/pl.netizens.imojesdk\/s23CustomStringConvertibleP","doc:\/\/pl.netizens.imojesdk\/SQ","doc:\/\/pl.netizens.imojesdk\/SH","doc:\/\/pl.netizens.imojesdk\/s8SendableP","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIAppearanceContainer","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIContentContainer","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIFocusEnvironment","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIResponderStandardEditActions","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIStateRestoring","doc:\/\/pl.netizens.imojesdk\/objc(pl)UITraitEnvironment","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGBankViewController","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"View Controller that allows user chooses bank method that he want to payment with"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGBankViewController"}],"title":"INGBankViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@iMojeSDK@objc(cs)INGBankViewController","modules":[{"name":"iMojeSDK"}],"navigatorTitle":[{"kind":"identifier","text":"INGBankViewController"}]},"hierarchy":{"paths":[["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGBankViewController\/init(banks:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGBankViewController\/bankSelected","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGBankViewController\/navigationBarTitle","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGBankViewController\/numbersOfColumn","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGBankViewController\/textForTitleLabel"]},{"title":"Instance Methods","identifiers":["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGBankViewController\/viewDidLoad()"]}],"references":{"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGBankViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGBankViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/imojesdk\/ingbankviewcontroller\/viewdidload()"},"doc://pl.netizens.imojesdk/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIContentContainer"},"doc://pl.netizens.imojesdk/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/pl.netizens.imojesdk\/SH"},"doc://pl.netizens.imojesdk/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)NSObject"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGBankViewController/bankSelected":{"role":"symbol","title":"bankSelected","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bankSelected"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"INGBank","preciseIdentifier":"c:@M@iMojeSDK@objc(cs)INGBank"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"Call when user select bank"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGBankViewController\/bankSelected","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk\/ingbankviewcontroller\/bankselected"},"doc://pl.netizens.imojesdk/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://pl.netizens.imojesdk/objc(cs)UIViewController":{"type":"unresolvable","title":"UIViewController","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(cs)UIViewController"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK":{"role":"collection","title":"iMojeSDK","abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk"},"doc://pl.netizens.imojesdk/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIFocusEnvironment"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGBankViewController/numbersOfColumn":{"role":"symbol","title":"numbersOfColumn","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"numbersOfColumn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"Number of column to be displayed"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGBankViewController\/numbersOfColumn","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk\/ingbankviewcontroller\/numbersofcolumn"},"doc://pl.netizens.imojesdk/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIStateRestoring"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGBankViewController":{"role":"symbol","title":"INGBankViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGBankViewController"}],"abstract":[{"type":"text","text":"View Controller that allows user chooses bank method that he want to payment with"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGBankViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"INGBankViewController"}],"url":"\/documentation\/imojesdk\/ingbankviewcontroller"},"doc://pl.netizens.imojesdk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/pl.netizens.imojesdk\/s28CustomDebugStringConvertibleP"},"doc://pl.netizens.imojesdk/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)NSCoding"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGBankViewController/init(banks:)":{"role":"symbol","title":"init(banks:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"banks"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"INGBank","preciseIdentifier":"c:@M@iMojeSDK@objc(cs)INGBank"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Create new "},{"type":"codeVoice","code":"INGBankViewController"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGBankViewController\/init(banks:)","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk\/ingbankviewcontroller\/init(banks:)"},"doc://pl.netizens.imojesdk/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIAppearanceContainer"},"doc://pl.netizens.imojesdk/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)NSExtensionRequestHandling"},"doc://pl.netizens.imojesdk/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/pl.netizens.imojesdk\/s7CVarArgP"},"doc://pl.netizens.imojesdk/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/pl.netizens.imojesdk\/SQ"},"doc://pl.netizens.imojesdk/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/pl.netizens.imojesdk\/s8SendableP"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGBankViewController/textForTitleLabel":{"role":"symbol","title":"textForTitleLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textForTitleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Title text for top label"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGBankViewController\/textForTitleLabel","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk\/ingbankviewcontroller\/textfortitlelabel"},"doc://pl.netizens.imojesdk/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UITraitEnvironment"},"doc://pl.netizens.imojesdk/7RxSwift18ReactiveCompatibleP":{"type":"unresolvable","title":"RxSwift.ReactiveCompatible","identifier":"doc:\/\/pl.netizens.imojesdk\/7RxSwift18ReactiveCompatibleP"},"doc://pl.netizens.imojesdk/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIPasteConfigurationSupporting"},"doc://pl.netizens.imojesdk/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIUserActivityRestoring"},"doc://pl.netizens.imojesdk/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIResponderStandardEditActions"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGBankViewController/navigationBarTitle":{"role":"symbol","title":"navigationBarTitle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationBarTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Title for Navigation item"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGBankViewController\/navigationBarTitle","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk\/ingbankviewcontroller\/navigationbartitle"},"doc://pl.netizens.imojesdk/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/pl.netizens.imojesdk\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"INGBankViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"INGBankViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"INGBankViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGBankViewController\/viewDidLoad()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/pl.netizens.imojesdk\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGBankViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGBankViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGBankViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGBankViewController\/title","value":"INGBankViewController"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGBankViewController\/fragments","value":[{"kind":"identifier","text":"INGBankViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}