{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGConfirmView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/imojesdk\/ingconfirmview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/imojesdk\/ingconfirmview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/pl.netizens.imojesdk\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/pl.netizens.imojesdk\/objc(pl)NSCoding","doc:\/\/pl.netizens.imojesdk\/objc(pl)NSObject","doc:\/\/pl.netizens.imojesdk\/objc(pl)CALayerDelegate","doc:\/\/pl.netizens.imojesdk\/7RxSwift18ReactiveCompatibleP","doc:\/\/pl.netizens.imojesdk\/s7CVarArgP","doc:\/\/pl.netizens.imojesdk\/s28CustomDebugStringConvertibleP","doc:\/\/pl.netizens.imojesdk\/s23CustomStringConvertibleP","doc:\/\/pl.netizens.imojesdk\/SQ","doc:\/\/pl.netizens.imojesdk\/SH","doc:\/\/pl.netizens.imojesdk\/s8SendableP","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIAccessibilityIdentification","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIAppearance","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIAppearanceContainer","doc:\/\/pl.netizens.imojesdk\/objc(pl)UICoordinateSpace","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIDynamicItem","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIFocusEnvironment","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIFocusItem","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIFocusItemContainer","doc:\/\/pl.netizens.imojesdk\/objc(pl)UILargeContentViewerItem","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIResponderStandardEditActions","doc:\/\/pl.netizens.imojesdk\/objc(pl)UITraitEnvironment","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGConfirmView","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"View that containts regulamins that user has accept"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGConfirmView"}],"title":"INGConfirmView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@iMojeSDK@objc(cs)INGConfirmView","modules":[{"name":"iMojeSDK"}],"navigatorTitle":[{"kind":"identifier","text":"INGConfirmView"}]},"hierarchy":{"paths":[["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGConfirmView\/init(confirm:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGConfirmView\/callback","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGConfirmView\/confirm"]}],"references":{"doc://pl.netizens.imojesdk/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)CALayerDelegate"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK":{"role":"collection","title":"iMojeSDK","abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGConfirmView":{"role":"symbol","title":"INGConfirmView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGConfirmView"}],"abstract":[{"type":"text","text":"View that containts regulamins that user has accept"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGConfirmView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"INGConfirmView"}],"url":"\/documentation\/imojesdk\/ingconfirmview"},"doc://pl.netizens.imojesdk/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIDynamicItem"},"doc://pl.netizens.imojesdk/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIFocusItemContainer"},"doc://pl.netizens.imojesdk/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIAppearance"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGConfirmView/confirm":{"role":"symbol","title":"confirm","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirm"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"INGConfirm","preciseIdentifier":"s:8iMojeSDK10INGConfirmV"}],"abstract":[{"type":"text","text":"Information that will be displayed in this screen"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGConfirmView\/confirm","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk\/ingconfirmview\/confirm"},"doc://pl.netizens.imojesdk/7RxSwift18ReactiveCompatibleP":{"type":"unresolvable","title":"RxSwift.ReactiveCompatible","identifier":"doc:\/\/pl.netizens.imojesdk\/7RxSwift18ReactiveCompatibleP"},"doc://pl.netizens.imojesdk/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/pl.netizens.imojesdk\/s7CVarArgP"},"doc://pl.netizens.imojesdk/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIResponderStandardEditActions"},"doc://pl.netizens.imojesdk/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIAccessibilityIdentification"},"doc://pl.netizens.imojesdk/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)NSObject"},"doc://pl.netizens.imojesdk/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://pl.netizens.imojesdk/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIAppearanceContainer"},"doc://pl.netizens.imojesdk/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)NSCoding"},"doc://pl.netizens.imojesdk/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UICoordinateSpace"},"doc://pl.netizens.imojesdk/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/pl.netizens.imojesdk\/SQ"},"doc://pl.netizens.imojesdk/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIFocusItem"},"doc://pl.netizens.imojesdk/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/pl.netizens.imojesdk\/s8SendableP"},"doc://pl.netizens.imojesdk/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/pl.netizens.imojesdk\/s23CustomStringConvertibleP"},"doc://pl.netizens.imojesdk/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(cs)UIView"},"doc://pl.netizens.imojesdk/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UITraitEnvironment"},"doc://pl.netizens.imojesdk/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGConfirmView/callback":{"role":"symbol","title":"callback","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"callback"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConfirmViewCallback","preciseIdentifier":"s:8iMojeSDK19ConfirmViewCallbacka"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Call when user tap “Pay” buttom to continue payment process"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGConfirmView\/callback","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk\/ingconfirmview\/callback"},"doc://pl.netizens.imojesdk/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIPasteConfigurationSupporting"},"doc://pl.netizens.imojesdk/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/pl.netizens.imojesdk\/SH"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGConfirmView/init(confirm:)":{"role":"symbol","title":"init(confirm:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"confirm"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"INGConfirm","preciseIdentifier":"s:8iMojeSDK10INGConfirmV"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Create new "},{"type":"codeVoice","code":"INGConfirmView"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGConfirmView\/init(confirm:)","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk\/ingconfirmview\/init(confirm:)"},"doc://pl.netizens.imojesdk/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIFocusEnvironment"},"doc://pl.netizens.imojesdk/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIUserActivityRestoring"},"doc://pl.netizens.imojesdk/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UILargeContentViewerItem"},"doc://pl.netizens.imojesdk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/pl.netizens.imojesdk\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"INGConfirmView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"INGConfirmView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"INGConfirmView"}]},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/pl.netizens.imojesdk\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGConfirmView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGConfirmView\/title","value":"INGConfirmView"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGConfirmView\/fragments","value":[{"kind":"identifier","text":"INGConfirmView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}