{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGConfirmViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/imojesdk\/ingconfirmviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/imojesdk\/ingconfirmviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/pl.netizens.imojesdk\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/pl.netizens.imojesdk\/objc(pl)NSCoding","doc:\/\/pl.netizens.imojesdk\/objc(pl)NSExtensionRequestHandling","doc:\/\/pl.netizens.imojesdk\/objc(pl)NSObject","doc:\/\/pl.netizens.imojesdk\/7RxSwift18ReactiveCompatibleP","doc:\/\/pl.netizens.imojesdk\/s7CVarArgP","doc:\/\/pl.netizens.imojesdk\/s28CustomDebugStringConvertibleP","doc:\/\/pl.netizens.imojesdk\/s23CustomStringConvertibleP","doc:\/\/pl.netizens.imojesdk\/SQ","doc:\/\/pl.netizens.imojesdk\/SH","doc:\/\/pl.netizens.imojesdk\/s8SendableP","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIAppearanceContainer","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIContentContainer","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIFocusEnvironment","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIResponderStandardEditActions","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIStateRestoring","doc:\/\/pl.netizens.imojesdk\/objc(pl)UITraitEnvironment","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGConfirmViewController","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"View Controller that containts regulamins that user has accept"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGConfirmViewController"}],"title":"INGConfirmViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@iMojeSDK@objc(cs)INGConfirmViewController","modules":[{"name":"iMojeSDK"}],"navigatorTitle":[{"kind":"identifier","text":"INGConfirmViewController"}]},"hierarchy":{"paths":[["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGConfirmViewController\/init(confirm:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGConfirmViewController\/callback","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGConfirmViewController\/confirm","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGConfirmViewController\/navigationBarTitle"]},{"title":"Instance Methods","identifiers":["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGConfirmViewController\/viewDidLoad()"]}],"references":{"doc://pl.netizens.imojesdk/7RxSwift18ReactiveCompatibleP":{"type":"unresolvable","title":"RxSwift.ReactiveCompatible","identifier":"doc:\/\/pl.netizens.imojesdk\/7RxSwift18ReactiveCompatibleP"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGConfirmViewController/init(confirm:)":{"role":"symbol","title":"init(confirm:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"confirm"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"INGConfirm","preciseIdentifier":"s:8iMojeSDK10INGConfirmV"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Create new "},{"type":"codeVoice","code":"INGConfirmViewController"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGConfirmViewController\/init(confirm:)","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk\/ingconfirmviewcontroller\/init(confirm:)"},"doc://pl.netizens.imojesdk/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIFocusEnvironment"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGConfirmViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGConfirmViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/imojesdk\/ingconfirmviewcontroller\/viewdidload()"},"doc://pl.netizens.imojesdk/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIPasteConfigurationSupporting"},"doc://pl.netizens.imojesdk/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/pl.netizens.imojesdk\/SH"},"doc://pl.netizens.imojesdk/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/pl.netizens.imojesdk\/SQ"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGConfirmViewController/callback":{"role":"symbol","title":"callback","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"callback"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConfirmViewCallback","preciseIdentifier":"s:8iMojeSDK19ConfirmViewCallbacka"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Call when user tap “Pay” buttom to continue payment process"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGConfirmViewController\/callback","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk\/ingconfirmviewcontroller\/callback"},"doc://pl.netizens.imojesdk/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)NSCoding"},"doc://pl.netizens.imojesdk/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIStateRestoring"},"doc://pl.netizens.imojesdk/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIAppearanceContainer"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK":{"role":"collection","title":"iMojeSDK","abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGConfirmViewController":{"role":"symbol","title":"INGConfirmViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGConfirmViewController"}],"abstract":[{"type":"text","text":"View Controller that containts regulamins that user has accept"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGConfirmViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"INGConfirmViewController"}],"url":"\/documentation\/imojesdk\/ingconfirmviewcontroller"},"doc://pl.netizens.imojesdk/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)NSExtensionRequestHandling"},"doc://pl.netizens.imojesdk/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://pl.netizens.imojesdk/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/pl.netizens.imojesdk\/s23CustomStringConvertibleP"},"doc://pl.netizens.imojesdk/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIContentContainer"},"doc://pl.netizens.imojesdk/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIUserActivityRestoring"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGConfirmViewController/confirm":{"role":"symbol","title":"confirm","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirm"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"INGConfirm","preciseIdentifier":"s:8iMojeSDK10INGConfirmV"}],"abstract":[{"type":"text","text":"Information that will be displayed in this screen"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGConfirmViewController\/confirm","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk\/ingconfirmviewcontroller\/confirm"},"doc://pl.netizens.imojesdk/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)NSObject"},"doc://pl.netizens.imojesdk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/pl.netizens.imojesdk\/s28CustomDebugStringConvertibleP"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGConfirmViewController/navigationBarTitle":{"role":"symbol","title":"navigationBarTitle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationBarTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Title for Navigation item"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGConfirmViewController\/navigationBarTitle","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk\/ingconfirmviewcontroller\/navigationbartitle"},"doc://pl.netizens.imojesdk/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UITraitEnvironment"},"doc://pl.netizens.imojesdk/objc(cs)UIViewController":{"type":"unresolvable","title":"UIViewController","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(cs)UIViewController"},"doc://pl.netizens.imojesdk/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/pl.netizens.imojesdk\/s8SendableP"},"doc://pl.netizens.imojesdk/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/pl.netizens.imojesdk\/s7CVarArgP"},"doc://pl.netizens.imojesdk/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIResponderStandardEditActions"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"INGConfirmViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"INGConfirmViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"INGConfirmViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGConfirmViewController\/viewDidLoad()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/pl.netizens.imojesdk\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGConfirmViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGConfirmViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGConfirmViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGConfirmViewController\/title","value":"INGConfirmViewController"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGConfirmViewController\/fragments","value":[{"kind":"identifier","text":"INGConfirmViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}