{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGChosePaymentMethodView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/imojesdk\/ingchosepaymentmethodview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/imojesdk\/ingchosepaymentmethodview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/pl.netizens.imojesdk\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/pl.netizens.imojesdk\/objc(pl)NSCoding","doc:\/\/pl.netizens.imojesdk\/objc(pl)NSObject","doc:\/\/pl.netizens.imojesdk\/objc(pl)CALayerDelegate","doc:\/\/pl.netizens.imojesdk\/7RxSwift18ReactiveCompatibleP","doc:\/\/pl.netizens.imojesdk\/s7CVarArgP","doc:\/\/pl.netizens.imojesdk\/s28CustomDebugStringConvertibleP","doc:\/\/pl.netizens.imojesdk\/s23CustomStringConvertibleP","doc:\/\/pl.netizens.imojesdk\/SQ","doc:\/\/pl.netizens.imojesdk\/SH","doc:\/\/pl.netizens.imojesdk\/s8SendableP","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIAccessibilityIdentification","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIAppearance","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIAppearanceContainer","doc:\/\/pl.netizens.imojesdk\/objc(pl)UICoordinateSpace","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIDynamicItem","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIFocusEnvironment","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIFocusItem","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIFocusItemContainer","doc:\/\/pl.netizens.imojesdk\/objc(pl)UILargeContentViewerItem","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIResponderStandardEditActions","doc:\/\/pl.netizens.imojesdk\/objc(pl)UITraitEnvironment","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGChosePaymentMethodView","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"View  that allows user chooses payment method that he want to payment with"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGChosePaymentMethodView"}],"title":"INGChosePaymentMethodView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@iMojeSDK@objc(cs)INGChosePaymentMethodView","modules":[{"name":"iMojeSDK"}],"navigatorTitle":[{"kind":"identifier","text":"INGChosePaymentMethodView"}]},"hierarchy":{"paths":[["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGChosePaymentMethodView\/init()"]},{"title":"Instance Properties","identifiers":["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGChosePaymentMethodView\/alwaysBounceVertical","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGChosePaymentMethodView\/customItems","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGChosePaymentMethodView\/itemSelected","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGChosePaymentMethodView\/shouldUseBuilInItems"]}],"references":{"doc://pl.netizens.imojesdk/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIFocusEnvironment"},"doc://pl.netizens.imojesdk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/pl.netizens.imojesdk\/s28CustomDebugStringConvertibleP"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK":{"role":"collection","title":"iMojeSDK","abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk"},"doc://pl.netizens.imojesdk/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/pl.netizens.imojesdk\/SQ"},"doc://pl.netizens.imojesdk/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)CALayerDelegate"},"doc://pl.netizens.imojesdk/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UITraitEnvironment"},"doc://pl.netizens.imojesdk/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UILargeContentViewerItem"},"doc://pl.netizens.imojesdk/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIUserActivityRestoring"},"doc://pl.netizens.imojesdk/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIAccessibilityIdentification"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGChosePaymentMethodView/itemSelected":{"role":"symbol","title":"itemSelected","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"itemSelected"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChosePaymentMethodViewItemSelected","preciseIdentifier":"s:8iMojeSDK34ChosePaymentMethodViewItemSelecteda"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Call when user select method"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGChosePaymentMethodView\/itemSelected","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk\/ingchosepaymentmethodview\/itemselected"},"doc://pl.netizens.imojesdk/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIFocusItem"},"doc://pl.netizens.imojesdk/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIAppearanceContainer"},"doc://pl.netizens.imojesdk/7RxSwift18ReactiveCompatibleP":{"type":"unresolvable","title":"RxSwift.ReactiveCompatible","identifier":"doc:\/\/pl.netizens.imojesdk\/7RxSwift18ReactiveCompatibleP"},"doc://pl.netizens.imojesdk/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/pl.netizens.imojesdk\/s7CVarArgP"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGChosePaymentMethodView/shouldUseBuilInItems":{"role":"symbol","title":"shouldUseBuilInItems","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldUseBuilInItems"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Should use also build in Payment Methods"},{"type":"text","text":" "},{"type":"text","text":"Default "},{"type":"codeVoice","code":"true"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGChosePaymentMethodView\/shouldUseBuilInItems","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk\/ingchosepaymentmethodview\/shouldusebuilinitems"},"doc://pl.netizens.imojesdk/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIDynamicItem"},"doc://pl.netizens.imojesdk/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://pl.netizens.imojesdk/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(cs)UIView"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGChosePaymentMethodView/customItems":{"role":"symbol","title":"customItems","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customItems"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"INGPaymentMethod","preciseIdentifier":"s:8iMojeSDK16INGPaymentMethodV"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Custom Payment Method that user can select"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGChosePaymentMethodView\/customItems","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk\/ingchosepaymentmethodview\/customitems"},"doc://pl.netizens.imojesdk/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UICoordinateSpace"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGChosePaymentMethodView/alwaysBounceVertical":{"role":"symbol","title":"alwaysBounceVertical","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"alwaysBounceVertical"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Bounce Vertical for TableView"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGChosePaymentMethodView\/alwaysBounceVertical","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk\/ingchosepaymentmethodview\/alwaysbouncevertical"},"doc://pl.netizens.imojesdk/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)NSCoding"},"doc://pl.netizens.imojesdk/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIPasteConfigurationSupporting"},"doc://pl.netizens.imojesdk/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/pl.netizens.imojesdk\/s8SendableP"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGChosePaymentMethodView/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Create new "},{"type":"codeVoice","code":"INGChosePaymentMethodView"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGChosePaymentMethodView\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/imojesdk\/ingchosepaymentmethodview\/init()"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGChosePaymentMethodView":{"role":"symbol","title":"INGChosePaymentMethodView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGChosePaymentMethodView"}],"abstract":[{"type":"text","text":"View  that allows user chooses payment method that he want to payment with"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGChosePaymentMethodView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"INGChosePaymentMethodView"}],"url":"\/documentation\/imojesdk\/ingchosepaymentmethodview"},"doc://pl.netizens.imojesdk/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)NSObject"},"doc://pl.netizens.imojesdk/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/pl.netizens.imojesdk\/SH"},"doc://pl.netizens.imojesdk/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/pl.netizens.imojesdk\/s23CustomStringConvertibleP"},"doc://pl.netizens.imojesdk/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIFocusItemContainer"},"doc://pl.netizens.imojesdk/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://pl.netizens.imojesdk/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIResponderStandardEditActions"},"doc://pl.netizens.imojesdk/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIAppearance"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"INGChosePaymentMethodView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"INGChosePaymentMethodView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"INGChosePaymentMethodView"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGChosePaymentMethodView\/init()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/pl.netizens.imojesdk\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGChosePaymentMethodView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGChosePaymentMethodView~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGChosePaymentMethodView~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGChosePaymentMethodView\/title","value":"INGChosePaymentMethodView"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGChosePaymentMethodView\/fragments","value":[{"kind":"identifier","text":"INGChosePaymentMethodView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}