{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGWebView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/imojesdk\/ingwebview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/imojesdk\/ingwebview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/pl.netizens.imojesdk\/objc(cs)UIStackView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/pl.netizens.imojesdk\/objc(pl)NSCoding","doc:\/\/pl.netizens.imojesdk\/objc(pl)NSObject","doc:\/\/pl.netizens.imojesdk\/objc(pl)CALayerDelegate","doc:\/\/pl.netizens.imojesdk\/7RxSwift18ReactiveCompatibleP","doc:\/\/pl.netizens.imojesdk\/s7CVarArgP","doc:\/\/pl.netizens.imojesdk\/s28CustomDebugStringConvertibleP","doc:\/\/pl.netizens.imojesdk\/s23CustomStringConvertibleP","doc:\/\/pl.netizens.imojesdk\/SQ","doc:\/\/pl.netizens.imojesdk\/SH","doc:\/\/pl.netizens.imojesdk\/s8SendableP","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIAccessibilityIdentification","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIAppearance","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIAppearanceContainer","doc:\/\/pl.netizens.imojesdk\/objc(pl)UICoordinateSpace","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIDynamicItem","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIFocusEnvironment","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIFocusItem","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIFocusItemContainer","doc:\/\/pl.netizens.imojesdk\/objc(pl)UILargeContentViewerItem","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIResponderStandardEditActions","doc:\/\/pl.netizens.imojesdk\/objc(pl)UITraitEnvironment","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIUserActivityRestoring","doc:\/\/pl.netizens.imojesdk\/objc(pl)WKNavigationDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGWebView","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"View  that shows web contents"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGWebView"}],"title":"INGWebView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@iMojeSDK@objc(cs)INGWebView","modules":[{"name":"iMojeSDK"}],"navigatorTitle":[{"kind":"identifier","text":"INGWebView"}]},"hierarchy":{"paths":[["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGWebView\/init(successRedirectURL:failureRedirectURL:disableURLQueryParameters:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGWebView\/disableURLQueryParameters","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGWebView\/failureRedirectURL","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGWebView\/onFailure","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGWebView\/onSuccess","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGWebView\/successRedirectURL"]},{"title":"Instance Methods","identifiers":["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGWebView\/load(content:)"]},{"title":"Type Properties","identifiers":["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGWebView\/hideAddress"]},{"title":"Default Implementations","identifiers":["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGWebView\/WKNavigationDelegate-Implementations"],"generated":true}],"references":{"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGWebView/init(successRedirectURL:failureRedirectURL:disableURLQueryParameters:)":{"role":"symbol","title":"init(successRedirectURL:failureRedirectURL:disableURLQueryParameters:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"successRedirectURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"failureRedirectURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"disableURLQueryParameters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Create new "},{"type":"codeVoice","code":"INGWebView"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGWebView\/init(successRedirectURL:failureRedirectURL:disableURLQueryParameters:)","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk\/ingwebview\/init(successredirecturl:failureredirecturl:disableurlqueryparameters:)"},"doc://pl.netizens.imojesdk/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIFocusItem"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGWebView":{"role":"symbol","title":"INGWebView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGWebView"}],"abstract":[{"type":"text","text":"View  that shows web contents"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGWebView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"INGWebView"}],"url":"\/documentation\/imojesdk\/ingwebview"},"doc://pl.netizens.imojesdk/7RxSwift18ReactiveCompatibleP":{"type":"unresolvable","title":"RxSwift.ReactiveCompatible","identifier":"doc:\/\/pl.netizens.imojesdk\/7RxSwift18ReactiveCompatibleP"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK":{"role":"collection","title":"iMojeSDK","abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk"},"doc://pl.netizens.imojesdk/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIDynamicItem"},"doc://pl.netizens.imojesdk/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGWebView/failureRedirectURL":{"role":"symbol","title":"failureRedirectURL","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureRedirectURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"URL that webview will call at the end of process"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGWebView\/failureRedirectURL","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk\/ingwebview\/failureredirecturl"},"doc://pl.netizens.imojesdk/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIResponderStandardEditActions"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGWebView/load(content:)":{"role":"symbol","title":"load(content:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"load"},{"kind":"text","text":"("},{"kind":"externalParam","text":"content"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"INGWebViewContent","preciseIdentifier":"s:8iMojeSDK17INGWebViewContentO"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Load content"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGWebView\/load(content:)","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk\/ingwebview\/load(content:)"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGWebView/onFailure":{"role":"symbol","title":"onFailure","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onFailure"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"Called when web view reachs "},{"type":"codeVoice","code":"failureRedirectURL"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGWebView\/onFailure","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk\/ingwebview\/onfailure"},"doc://pl.netizens.imojesdk/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UITraitEnvironment"},"doc://pl.netizens.imojesdk/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/pl.netizens.imojesdk\/s7CVarArgP"},"doc://pl.netizens.imojesdk/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UILargeContentViewerItem"},"doc://pl.netizens.imojesdk/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIAccessibilityIdentification"},"doc://pl.netizens.imojesdk/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/pl.netizens.imojesdk\/SQ"},"doc://pl.netizens.imojesdk/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)NSObject"},"doc://pl.netizens.imojesdk/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://pl.netizens.imojesdk/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/pl.netizens.imojesdk\/s8SendableP"},"doc://pl.netizens.imojesdk/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/pl.netizens.imojesdk\/s23CustomStringConvertibleP"},"doc://pl.netizens.imojesdk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/pl.netizens.imojesdk\/s28CustomDebugStringConvertibleP"},"doc://pl.netizens.imojesdk/objc(cs)UIStackView":{"type":"unresolvable","title":"UIStackView","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(cs)UIStackView"},"doc://pl.netizens.imojesdk/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIPasteConfigurationSupporting"},"doc://pl.netizens.imojesdk/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIAppearance"},"doc://pl.netizens.imojesdk/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIFocusItemContainer"},"doc://pl.netizens.imojesdk/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)NSCoding"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGWebView/WKNavigationDelegate-Implementations":{"role":"collectionGroup","title":"WKNavigationDelegate Implementations","abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGWebView\/WKNavigationDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/imojesdk\/ingwebview\/wknavigationdelegate-implementations"},"doc://pl.netizens.imojesdk/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)CALayerDelegate"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGWebView/hideAddress":{"role":"symbol","title":"hideAddress","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hideAddress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Hidde adrdress URL on the top of WebView, Default value is "},{"type":"codeVoice","code":"false"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGWebView\/hideAddress","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk\/ingwebview\/hideaddress"},"doc://pl.netizens.imojesdk/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIFocusEnvironment"},"doc://pl.netizens.imojesdk/objc(pl)WKNavigationDelegate":{"type":"unresolvable","title":"WebKit.WKNavigationDelegate","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)WKNavigationDelegate"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGWebView/successRedirectURL":{"role":"symbol","title":"successRedirectURL","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"successRedirectURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"URL that webview will call at the end of process"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGWebView\/successRedirectURL","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk\/ingwebview\/successredirecturl"},"doc://pl.netizens.imojesdk/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/pl.netizens.imojesdk\/SH"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGWebView/onSuccess":{"role":"symbol","title":"onSuccess","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSuccess"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[{"type":"text","text":"Called when web view reachs "},{"type":"codeVoice","code":"successRedirectURL"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGWebView\/onSuccess","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk\/ingwebview\/onsuccess"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/INGWebView/disableURLQueryParameters":{"role":"symbol","title":"disableURLQueryParameters","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableURLQueryParameters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Remove paramters from success and failure redirect url"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGWebView\/disableURLQueryParameters","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk\/ingwebview\/disableurlqueryparameters"},"doc://pl.netizens.imojesdk/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIUserActivityRestoring"},"doc://pl.netizens.imojesdk/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UICoordinateSpace"},"doc://pl.netizens.imojesdk/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIAppearanceContainer"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"INGWebView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"INGWebView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"INGWebView"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Default Implementations","identifiers":["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/INGWebView\/WKNavigationDelegate-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/pl.netizens.imojesdk\/objc(cs)UIStackView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"INGWebView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIStackView","preciseIdentifier":"c:objc(cs)UIStackView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGWebView\/title","value":"INGWebView"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1INGWebView\/fragments","value":[{"kind":"identifier","text":"INGWebView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}