{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentMethodCodeViewCell"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/imojesdk\/paymentmethodcodeviewcell"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/imojesdk\/paymentmethodcodeviewcell"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/pl.netizens.imojesdk\/objc(cs)UICollectionViewCell"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/pl.netizens.imojesdk\/objc(pl)NSCoding","doc:\/\/pl.netizens.imojesdk\/objc(pl)NSObject","doc:\/\/pl.netizens.imojesdk\/objc(pl)CALayerDelegate","doc:\/\/pl.netizens.imojesdk\/7RxSwift18ReactiveCompatibleP","doc:\/\/pl.netizens.imojesdk\/s7CVarArgP","doc:\/\/pl.netizens.imojesdk\/s28CustomDebugStringConvertibleP","doc:\/\/pl.netizens.imojesdk\/s23CustomStringConvertibleP","doc:\/\/pl.netizens.imojesdk\/SQ","doc:\/\/pl.netizens.imojesdk\/SH","doc:\/\/pl.netizens.imojesdk\/s8SendableP","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIAccessibilityIdentification","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIAppearance","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIAppearanceContainer","doc:\/\/pl.netizens.imojesdk\/objc(pl)UICoordinateSpace","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIDynamicItem","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIFocusEnvironment","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIFocusItem","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIFocusItemContainer","doc:\/\/pl.netizens.imojesdk\/objc(pl)UILargeContentViewerItem","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIResponderStandardEditActions","doc:\/\/pl.netizens.imojesdk\/objc(pl)UITraitEnvironment","doc:\/\/pl.netizens.imojesdk\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/PaymentMethodCodeViewCell","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Payment method code item view"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentMethodCodeViewCell"}],"title":"PaymentMethodCodeViewCell","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@iMojeSDK@objc(cs)PaymentMethodCodeViewCell","modules":[{"name":"iMojeSDK"}],"navigatorTitle":[{"kind":"identifier","text":"PaymentMethodCodeViewCell"}]},"hierarchy":{"paths":[["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/PaymentMethodCodeViewCell\/borderColor","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/PaymentMethodCodeViewCell\/borderWidth","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/PaymentMethodCodeViewCell\/cornerRadius","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/PaymentMethodCodeViewCell\/offlineBackgroundColor","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/PaymentMethodCodeViewCell\/onlineBackgroundColor","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/PaymentMethodCodeViewCell\/padding","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/PaymentMethodCodeViewCell\/selectedBorderColor"]},{"title":"Instance Methods","identifiers":["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/PaymentMethodCodeViewCell\/prepareForReuse()"]}],"references":{"doc://pl.netizens.imojesdk/documentation/iMojeSDK/PaymentMethodCodeViewCell/padding":{"role":"symbol","title":"padding","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"padding"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"padding of image"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/PaymentMethodCodeViewCell\/padding","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"padding"}],"url":"\/documentation\/imojesdk\/paymentmethodcodeviewcell\/padding"},"doc://pl.netizens.imojesdk/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIDynamicItem"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/PaymentMethodCodeViewCell/selectedBorderColor":{"role":"symbol","title":"selectedBorderColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedBorderColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGColor","preciseIdentifier":"c:@T@CGColorRef"}],"abstract":[{"type":"text","text":"selected border color"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/PaymentMethodCodeViewCell\/selectedBorderColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"selectedBorderColor"}],"url":"\/documentation\/imojesdk\/paymentmethodcodeviewcell\/selectedbordercolor"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/PaymentMethodCodeViewCell":{"role":"symbol","title":"PaymentMethodCodeViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentMethodCodeViewCell"}],"abstract":[{"type":"text","text":"Payment method code item view"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/PaymentMethodCodeViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PaymentMethodCodeViewCell"}],"url":"\/documentation\/imojesdk\/paymentmethodcodeviewcell"},"doc://pl.netizens.imojesdk/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/pl.netizens.imojesdk\/s23CustomStringConvertibleP"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/PaymentMethodCodeViewCell/prepareForReuse()":{"role":"symbol","title":"prepareForReuse()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepareForReuse"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":":nodoc:"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/PaymentMethodCodeViewCell\/prepareForReuse()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"prepareForReuse"}],"url":"\/documentation\/imojesdk\/paymentmethodcodeviewcell\/prepareforreuse()"},"doc://pl.netizens.imojesdk/7RxSwift18ReactiveCompatibleP":{"type":"unresolvable","title":"RxSwift.ReactiveCompatible","identifier":"doc:\/\/pl.netizens.imojesdk\/7RxSwift18ReactiveCompatibleP"},"doc://pl.netizens.imojesdk/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIPasteConfigurationSupporting"},"doc://pl.netizens.imojesdk/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIResponderStandardEditActions"},"doc://pl.netizens.imojesdk/objc(cs)UICollectionViewCell":{"type":"unresolvable","title":"UICollectionViewCell","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(cs)UICollectionViewCell"},"doc://pl.netizens.imojesdk/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)CALayerDelegate"},"doc://pl.netizens.imojesdk/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://pl.netizens.imojesdk/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)NSCoding"},"doc://pl.netizens.imojesdk/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/pl.netizens.imojesdk\/s8SendableP"},"doc://pl.netizens.imojesdk/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIUserActivityRestoring"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK":{"role":"collection","title":"iMojeSDK","abstract":[],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK","kind":"symbol","type":"topic","url":"\/documentation\/imojesdk"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/PaymentMethodCodeViewCell/borderWidth":{"role":"symbol","title":"borderWidth","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"borderWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"border width"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/PaymentMethodCodeViewCell\/borderWidth","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"borderWidth"}],"url":"\/documentation\/imojesdk\/paymentmethodcodeviewcell\/borderwidth"},"doc://pl.netizens.imojesdk/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UILargeContentViewerItem"},"doc://pl.netizens.imojesdk/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)NSObject"},"doc://pl.netizens.imojesdk/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIFocusEnvironment"},"doc://pl.netizens.imojesdk/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIFocusItem"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/PaymentMethodCodeViewCell/cornerRadius":{"role":"symbol","title":"cornerRadius","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cornerRadius"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"corner radius"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/PaymentMethodCodeViewCell\/cornerRadius","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cornerRadius"}],"url":"\/documentation\/imojesdk\/paymentmethodcodeviewcell\/cornerradius"},"doc://pl.netizens.imojesdk/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIFocusItemContainer"},"doc://pl.netizens.imojesdk/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/pl.netizens.imojesdk\/SQ"},"doc://pl.netizens.imojesdk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/pl.netizens.imojesdk\/s28CustomDebugStringConvertibleP"},"doc://pl.netizens.imojesdk/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIAppearance"},"doc://pl.netizens.imojesdk/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIAccessibilityIdentification"},"doc://pl.netizens.imojesdk/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIAppearanceContainer"},"doc://pl.netizens.imojesdk/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/pl.netizens.imojesdk\/s7CVarArgP"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/PaymentMethodCodeViewCell/borderColor":{"role":"symbol","title":"borderColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"borderColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGColor","preciseIdentifier":"c:@T@CGColorRef"}],"abstract":[{"type":"text","text":"border color"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/PaymentMethodCodeViewCell\/borderColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"borderColor"}],"url":"\/documentation\/imojesdk\/paymentmethodcodeviewcell\/bordercolor"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/PaymentMethodCodeViewCell/offlineBackgroundColor":{"role":"symbol","title":"offlineBackgroundColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"offlineBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"background color when method is offline"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/PaymentMethodCodeViewCell\/offlineBackgroundColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"offlineBackgroundColor"}],"url":"\/documentation\/imojesdk\/paymentmethodcodeviewcell\/offlinebackgroundcolor"},"doc://pl.netizens.imojesdk/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UITraitEnvironment"},"doc://pl.netizens.imojesdk/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/pl.netizens.imojesdk\/SH"},"doc://pl.netizens.imojesdk/documentation/iMojeSDK/PaymentMethodCodeViewCell/onlineBackgroundColor":{"role":"symbol","title":"onlineBackgroundColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"onlineBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"background color when method is online"}],"identifier":"doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/PaymentMethodCodeViewCell\/onlineBackgroundColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onlineBackgroundColor"}],"url":"\/documentation\/imojesdk\/paymentmethodcodeviewcell\/onlinebackgroundcolor"},"doc://pl.netizens.imojesdk/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://pl.netizens.imojesdk/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/pl.netizens.imojesdk\/objc(pl)UICoordinateSpace"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"PaymentMethodCodeViewCell"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PaymentMethodCodeViewCell"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PaymentMethodCodeViewCell"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/PaymentMethodCodeViewCell\/borderColor","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/PaymentMethodCodeViewCell\/borderWidth","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/PaymentMethodCodeViewCell\/cornerRadius","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/PaymentMethodCodeViewCell\/offlineBackgroundColor","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/PaymentMethodCodeViewCell\/onlineBackgroundColor","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/PaymentMethodCodeViewCell\/padding","doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/PaymentMethodCodeViewCell\/selectedBorderColor"]},{"title":"Instance Methods","identifiers":["doc:\/\/pl.netizens.imojesdk\/documentation\/iMojeSDK\/PaymentMethodCodeViewCell\/prepareForReuse()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/pl.netizens.imojesdk\/objc(cs)UICollectionViewCell"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentMethodCodeViewCell"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UICollectionViewCell","preciseIdentifier":"c:objc(cs)UICollectionViewCell"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1PaymentMethodCodeViewCell~1padding\/title","value":"padding"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1PaymentMethodCodeViewCell~1padding\/fragments","value":[{"kind":"identifier","text":"padding"}]},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1PaymentMethodCodeViewCell~1selectedBorderColor\/title","value":"selectedBorderColor"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1PaymentMethodCodeViewCell~1selectedBorderColor\/fragments","value":[{"kind":"identifier","text":"selectedBorderColor"}]},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1PaymentMethodCodeViewCell\/title","value":"PaymentMethodCodeViewCell"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1PaymentMethodCodeViewCell\/fragments","value":[{"kind":"identifier","text":"PaymentMethodCodeViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1PaymentMethodCodeViewCell~1prepareForReuse()\/title","value":"prepareForReuse"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1PaymentMethodCodeViewCell~1prepareForReuse()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"prepareForReuse"}]},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1PaymentMethodCodeViewCell~1borderWidth\/title","value":"borderWidth"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1PaymentMethodCodeViewCell~1borderWidth\/fragments","value":[{"kind":"identifier","text":"borderWidth"}]},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1PaymentMethodCodeViewCell~1cornerRadius\/title","value":"cornerRadius"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1PaymentMethodCodeViewCell~1cornerRadius\/fragments","value":[{"kind":"identifier","text":"cornerRadius"}]},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1PaymentMethodCodeViewCell~1borderColor\/title","value":"borderColor"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1PaymentMethodCodeViewCell~1borderColor\/fragments","value":[{"kind":"identifier","text":"borderColor"}]},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1PaymentMethodCodeViewCell~1offlineBackgroundColor\/title","value":"offlineBackgroundColor"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1PaymentMethodCodeViewCell~1offlineBackgroundColor\/fragments","value":[{"kind":"identifier","text":"offlineBackgroundColor"}]},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1PaymentMethodCodeViewCell~1onlineBackgroundColor\/title","value":"onlineBackgroundColor"},{"op":"replace","path":"\/references\/doc:~1~1pl.netizens.imojesdk~1documentation~1iMojeSDK~1PaymentMethodCodeViewCell~1onlineBackgroundColor\/fragments","value":[{"kind":"identifier","text":"onlineBackgroundColor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}